// Generated by gencpp from file aqua_gait/UpdateTargetRPYD.msg
// DO NOT EDIT!


#ifndef AQUA_GAIT_MESSAGE_UPDATETARGETRPYD_H
#define AQUA_GAIT_MESSAGE_UPDATETARGETRPYD_H

#include <ros/service_traits.h>


#include <aqua_gait/UpdateTargetRPYDRequest.h>
#include <aqua_gait/UpdateTargetRPYDResponse.h>


namespace aqua_gait
{

struct UpdateTargetRPYD
{

typedef UpdateTargetRPYDRequest Request;
typedef UpdateTargetRPYDResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UpdateTargetRPYD
} // namespace aqua_gait


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aqua_gait::UpdateTargetRPYD > {
  static const char* value()
  {
    return "67eb34f7772a72c0462945d31ff2da84";
  }

  static const char* value(const ::aqua_gait::UpdateTargetRPYD&) { return value(); }
};

template<>
struct DataType< ::aqua_gait::UpdateTargetRPYD > {
  static const char* value()
  {
    return "aqua_gait/UpdateTargetRPYD";
  }

  static const char* value(const ::aqua_gait::UpdateTargetRPYD&) { return value(); }
};


// service_traits::MD5Sum< ::aqua_gait::UpdateTargetRPYDRequest> should match 
// service_traits::MD5Sum< ::aqua_gait::UpdateTargetRPYD > 
template<>
struct MD5Sum< ::aqua_gait::UpdateTargetRPYDRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aqua_gait::UpdateTargetRPYD >::value();
  }
  static const char* value(const ::aqua_gait::UpdateTargetRPYDRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aqua_gait::UpdateTargetRPYDRequest> should match 
// service_traits::DataType< ::aqua_gait::UpdateTargetRPYD > 
template<>
struct DataType< ::aqua_gait::UpdateTargetRPYDRequest>
{
  static const char* value()
  {
    return DataType< ::aqua_gait::UpdateTargetRPYD >::value();
  }
  static const char* value(const ::aqua_gait::UpdateTargetRPYDRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aqua_gait::UpdateTargetRPYDResponse> should match 
// service_traits::MD5Sum< ::aqua_gait::UpdateTargetRPYD > 
template<>
struct MD5Sum< ::aqua_gait::UpdateTargetRPYDResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aqua_gait::UpdateTargetRPYD >::value();
  }
  static const char* value(const ::aqua_gait::UpdateTargetRPYDResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aqua_gait::UpdateTargetRPYDResponse> should match 
// service_traits::DataType< ::aqua_gait::UpdateTargetRPYD > 
template<>
struct DataType< ::aqua_gait::UpdateTargetRPYDResponse>
{
  static const char* value()
  {
    return DataType< ::aqua_gait::UpdateTargetRPYD >::value();
  }
  static const char* value(const ::aqua_gait::UpdateTargetRPYDResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AQUA_GAIT_MESSAGE_UPDATETARGETRPYD_H
