; Auto-generated. Do not edit!


(cl:in-package aquacore-msg)


;//! \htmlinclude ChangeDepthFeedback.msg.html

(cl:defclass <ChangeDepthFeedback> (roslisp-msg-protocol:ros-message)
  ((percent_depth_change_completed
    :reader percent_depth_change_completed
    :initarg :percent_depth_change_completed
    :type cl:float
    :initform 0.0))
)

(cl:defclass ChangeDepthFeedback (<ChangeDepthFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ChangeDepthFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ChangeDepthFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name aquacore-msg:<ChangeDepthFeedback> is deprecated: use aquacore-msg:ChangeDepthFeedback instead.")))

(cl:ensure-generic-function 'percent_depth_change_completed-val :lambda-list '(m))
(cl:defmethod percent_depth_change_completed-val ((m <ChangeDepthFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader aquacore-msg:percent_depth_change_completed-val is deprecated.  Use aquacore-msg:percent_depth_change_completed instead.")
  (percent_depth_change_completed m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ChangeDepthFeedback>) ostream)
  "Serializes a message object of type '<ChangeDepthFeedback>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'percent_depth_change_completed))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ChangeDepthFeedback>) istream)
  "Deserializes a message object of type '<ChangeDepthFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'percent_depth_change_completed) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ChangeDepthFeedback>)))
  "Returns string type for a message object of type '<ChangeDepthFeedback>"
  "aquacore/ChangeDepthFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ChangeDepthFeedback)))
  "Returns string type for a message object of type 'ChangeDepthFeedback"
  "aquacore/ChangeDepthFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ChangeDepthFeedback>)))
  "Returns md5sum for a message object of type '<ChangeDepthFeedback>"
  "fb4840ab3fac3d08d9262a1a6b1c2c09")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ChangeDepthFeedback)))
  "Returns md5sum for a message object of type 'ChangeDepthFeedback"
  "fb4840ab3fac3d08d9262a1a6b1c2c09")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ChangeDepthFeedback>)))
  "Returns full string definition for message of type '<ChangeDepthFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# Feedback~%float64 percent_depth_change_completed~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ChangeDepthFeedback)))
  "Returns full string definition for message of type 'ChangeDepthFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# Feedback~%float64 percent_depth_change_completed~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ChangeDepthFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ChangeDepthFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'ChangeDepthFeedback
    (cl:cons ':percent_depth_change_completed (percent_depth_change_completed msg))
))
