; Auto-generated. Do not edit!


(cl:in-package aquacore-msg)


;//! \htmlinclude ChangeDepthGoal.msg.html

(cl:defclass <ChangeDepthGoal> (roslisp-msg-protocol:ros-message)
  ((depth
    :reader depth
    :initarg :depth
    :type cl:float
    :initform 0.0)
   (speed
    :reader speed
    :initarg :speed
    :type cl:float
    :initform 0.0))
)

(cl:defclass ChangeDepthGoal (<ChangeDepthGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <ChangeDepthGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'ChangeDepthGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name aquacore-msg:<ChangeDepthGoal> is deprecated: use aquacore-msg:ChangeDepthGoal instead.")))

(cl:ensure-generic-function 'depth-val :lambda-list '(m))
(cl:defmethod depth-val ((m <ChangeDepthGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader aquacore-msg:depth-val is deprecated.  Use aquacore-msg:depth instead.")
  (depth m))

(cl:ensure-generic-function 'speed-val :lambda-list '(m))
(cl:defmethod speed-val ((m <ChangeDepthGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader aquacore-msg:speed-val is deprecated.  Use aquacore-msg:speed instead.")
  (speed m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <ChangeDepthGoal>) ostream)
  "Serializes a message object of type '<ChangeDepthGoal>"
  (cl:let ((bits (roslisp-utils:encode-single-float-bits (cl:slot-value msg 'depth))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream))
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'speed))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <ChangeDepthGoal>) istream)
  "Deserializes a message object of type '<ChangeDepthGoal>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'depth) (roslisp-utils:decode-single-float-bits bits)))
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'speed) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<ChangeDepthGoal>)))
  "Returns string type for a message object of type '<ChangeDepthGoal>"
  "aquacore/ChangeDepthGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'ChangeDepthGoal)))
  "Returns string type for a message object of type 'ChangeDepthGoal"
  "aquacore/ChangeDepthGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<ChangeDepthGoal>)))
  "Returns md5sum for a message object of type '<ChangeDepthGoal>"
  "4c547ce0c0ba6eb4d0a01719590b156a")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'ChangeDepthGoal)))
  "Returns md5sum for a message object of type 'ChangeDepthGoal"
  "4c547ce0c0ba6eb4d0a01719590b156a")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<ChangeDepthGoal>)))
  "Returns full string definition for message of type '<ChangeDepthGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Desired Goal~%float32 depth # in m (be weary of depth sensor's constant depth offset)~%float64 speed # in m/s (using depth autopilot) or pseudo-unit-rate (using angles autopilot)~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'ChangeDepthGoal)))
  "Returns full string definition for message of type 'ChangeDepthGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Desired Goal~%float32 depth # in m (be weary of depth sensor's constant depth offset)~%float64 speed # in m/s (using depth autopilot) or pseudo-unit-rate (using angles autopilot)~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <ChangeDepthGoal>))
  (cl:+ 0
     4
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <ChangeDepthGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'ChangeDepthGoal
    (cl:cons ':depth (depth msg))
    (cl:cons ':speed (speed msg))
))
