; Auto-generated. Do not edit!


(cl:in-package aquacore-msg)


;//! \htmlinclude DoSurfaceTaskResult.msg.html

(cl:defclass <DoSurfaceTaskResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass DoSurfaceTaskResult (<DoSurfaceTaskResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <DoSurfaceTaskResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'DoSurfaceTaskResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name aquacore-msg:<DoSurfaceTaskResult> is deprecated: use aquacore-msg:DoSurfaceTaskResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <DoSurfaceTaskResult>) ostream)
  "Serializes a message object of type '<DoSurfaceTaskResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <DoSurfaceTaskResult>) istream)
  "Deserializes a message object of type '<DoSurfaceTaskResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<DoSurfaceTaskResult>)))
  "Returns string type for a message object of type '<DoSurfaceTaskResult>"
  "aquacore/DoSurfaceTaskResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'DoSurfaceTaskResult)))
  "Returns string type for a message object of type 'DoSurfaceTaskResult"
  "aquacore/DoSurfaceTaskResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<DoSurfaceTaskResult>)))
  "Returns md5sum for a message object of type '<DoSurfaceTaskResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'DoSurfaceTaskResult)))
  "Returns md5sum for a message object of type 'DoSurfaceTaskResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<DoSurfaceTaskResult>)))
  "Returns full string definition for message of type '<DoSurfaceTaskResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# Result~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'DoSurfaceTaskResult)))
  "Returns full string definition for message of type 'DoSurfaceTaskResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# Result~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <DoSurfaceTaskResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <DoSurfaceTaskResult>))
  "Converts a ROS message object to a list"
  (cl:list 'DoSurfaceTaskResult
))
