; Auto-generated. Do not edit!


(cl:in-package aquacore-msg)


;//! \htmlinclude GotoFeedback.msg.html

(cl:defclass <GotoFeedback> (roslisp-msg-protocol:ros-message)
  ((current_waypoint
    :reader current_waypoint
    :initarg :current_waypoint
    :type geometry_msgs-msg:Pose
    :initform (cl:make-instance 'geometry_msgs-msg:Pose)))
)

(cl:defclass GotoFeedback (<GotoFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GotoFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GotoFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name aquacore-msg:<GotoFeedback> is deprecated: use aquacore-msg:GotoFeedback instead.")))

(cl:ensure-generic-function 'current_waypoint-val :lambda-list '(m))
(cl:defmethod current_waypoint-val ((m <GotoFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader aquacore-msg:current_waypoint-val is deprecated.  Use aquacore-msg:current_waypoint instead.")
  (current_waypoint m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GotoFeedback>) ostream)
  "Serializes a message object of type '<GotoFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'current_waypoint) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GotoFeedback>) istream)
  "Deserializes a message object of type '<GotoFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'current_waypoint) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GotoFeedback>)))
  "Returns string type for a message object of type '<GotoFeedback>"
  "aquacore/GotoFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GotoFeedback)))
  "Returns string type for a message object of type 'GotoFeedback"
  "aquacore/GotoFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GotoFeedback>)))
  "Returns md5sum for a message object of type '<GotoFeedback>"
  "1996e7f170eaa92091d553f10efda1ee")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GotoFeedback)))
  "Returns md5sum for a message object of type 'GotoFeedback"
  "1996e7f170eaa92091d553f10efda1ee")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GotoFeedback>)))
  "Returns full string definition for message of type '<GotoFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# Feedback ~%~%# Current position and orientation. ~%# Semantics as above.~%geometry_msgs/Pose current_waypoint~%~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of postion and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GotoFeedback)))
  "Returns full string definition for message of type 'GotoFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# Feedback ~%~%# Current position and orientation. ~%# Semantics as above.~%geometry_msgs/Pose current_waypoint~%~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of postion and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GotoFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'current_waypoint))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GotoFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'GotoFeedback
    (cl:cons ':current_waypoint (current_waypoint msg))
))
