; Auto-generated. Do not edit!


(cl:in-package aquacore-msg)


;//! \htmlinclude GotoResult.msg.html

(cl:defclass <GotoResult> (roslisp-msg-protocol:ros-message)
  ((arrived_successfully
    :reader arrived_successfully
    :initarg :arrived_successfully
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass GotoResult (<GotoResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GotoResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GotoResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name aquacore-msg:<GotoResult> is deprecated: use aquacore-msg:GotoResult instead.")))

(cl:ensure-generic-function 'arrived_successfully-val :lambda-list '(m))
(cl:defmethod arrived_successfully-val ((m <GotoResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader aquacore-msg:arrived_successfully-val is deprecated.  Use aquacore-msg:arrived_successfully instead.")
  (arrived_successfully m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GotoResult>) ostream)
  "Serializes a message object of type '<GotoResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'arrived_successfully) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GotoResult>) istream)
  "Deserializes a message object of type '<GotoResult>"
    (cl:setf (cl:slot-value msg 'arrived_successfully) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GotoResult>)))
  "Returns string type for a message object of type '<GotoResult>"
  "aquacore/GotoResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GotoResult)))
  "Returns string type for a message object of type 'GotoResult"
  "aquacore/GotoResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GotoResult>)))
  "Returns md5sum for a message object of type '<GotoResult>"
  "d67e2e7ba3581d5761cc209bedbe1209")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GotoResult)))
  "Returns md5sum for a message object of type 'GotoResult"
  "d67e2e7ba3581d5761cc209bedbe1209")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GotoResult>)))
  "Returns full string definition for message of type '<GotoResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# Result~%~%bool arrived_successfully~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GotoResult)))
  "Returns full string definition for message of type 'GotoResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# Result~%~%bool arrived_successfully~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GotoResult>))
  (cl:+ 0
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GotoResult>))
  "Converts a ROS message object to a list"
  (cl:list 'GotoResult
    (cl:cons ':arrived_successfully (arrived_successfully msg))
))
