; Auto-generated. Do not edit!


(cl:in-package aquacore-msg)


;//! \htmlinclude GotoGoal.msg.html

(cl:defclass <GotoGoal> (roslisp-msg-protocol:ros-message)
  ((target_waypoint
    :reader target_waypoint
    :initarg :target_waypoint
    :type geometry_msgs-msg:Pose
    :initform (cl:make-instance 'geometry_msgs-msg:Pose))
   (start_towards_last_bearing
    :reader start_towards_last_bearing
    :initarg :start_towards_last_bearing
    :type cl:boolean
    :initform cl:nil))
)

(cl:defclass GotoGoal (<GotoGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <GotoGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'GotoGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name aquacore-msg:<GotoGoal> is deprecated: use aquacore-msg:GotoGoal instead.")))

(cl:ensure-generic-function 'target_waypoint-val :lambda-list '(m))
(cl:defmethod target_waypoint-val ((m <GotoGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader aquacore-msg:target_waypoint-val is deprecated.  Use aquacore-msg:target_waypoint instead.")
  (target_waypoint m))

(cl:ensure-generic-function 'start_towards_last_bearing-val :lambda-list '(m))
(cl:defmethod start_towards_last_bearing-val ((m <GotoGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader aquacore-msg:start_towards_last_bearing-val is deprecated.  Use aquacore-msg:start_towards_last_bearing instead.")
  (start_towards_last_bearing m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <GotoGoal>) ostream)
  "Serializes a message object of type '<GotoGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'target_waypoint) ostream)
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'start_towards_last_bearing) 1 0)) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <GotoGoal>) istream)
  "Deserializes a message object of type '<GotoGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'target_waypoint) istream)
    (cl:setf (cl:slot-value msg 'start_towards_last_bearing) (cl:not (cl:zerop (cl:read-byte istream))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<GotoGoal>)))
  "Returns string type for a message object of type '<GotoGoal>"
  "aquacore/GotoGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'GotoGoal)))
  "Returns string type for a message object of type 'GotoGoal"
  "aquacore/GotoGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<GotoGoal>)))
  "Returns md5sum for a message object of type '<GotoGoal>"
  "5fbff635c879e970e24112664f7e3eb1")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'GotoGoal)))
  "Returns md5sum for a message object of type 'GotoGoal"
  "5fbff635c879e970e24112664f7e3eb1")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<GotoGoal>)))
  "Returns full string definition for message of type '<GotoGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Desired goal~%~%# (x,y) denotes latitude and longitude respectively (in degrees)~%# z denotes depth, > 0 above the water, 0 on the surface, < 0 underwater (in meters)~%# orientation is currently not handled ~%geometry_msgs/Pose target_waypoint~%~%# True if we want to avoid a random step to initialize the global heading of the robot ~%# and instead use the last known heading from the previous goal. ~%# This is useful when we have a chain of goals to reach, one after the other, because~%# it avoids ugly turns in the beginning of the trajectory towards the next goal..~%bool   start_towards_last_bearing ~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of postion and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'GotoGoal)))
  "Returns full string definition for message of type 'GotoGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Desired goal~%~%# (x,y) denotes latitude and longitude respectively (in degrees)~%# z denotes depth, > 0 above the water, 0 on the surface, < 0 underwater (in meters)~%# orientation is currently not handled ~%geometry_msgs/Pose target_waypoint~%~%# True if we want to avoid a random step to initialize the global heading of the robot ~%# and instead use the last known heading from the previous goal. ~%# This is useful when we have a chain of goals to reach, one after the other, because~%# it avoids ugly turns in the beginning of the trajectory towards the next goal..~%bool   start_towards_last_bearing ~%~%================================================================================~%MSG: geometry_msgs/Pose~%# A representation of pose in free space, composed of postion and orientation. ~%Point position~%Quaternion orientation~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%================================================================================~%MSG: geometry_msgs/Quaternion~%# This represents an orientation in free space in quaternion form.~%~%float64 x~%float64 y~%float64 z~%float64 w~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <GotoGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'target_waypoint))
     1
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <GotoGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'GotoGoal
    (cl:cons ':target_waypoint (target_waypoint msg))
    (cl:cons ':start_towards_last_bearing (start_towards_last_bearing msg))
))
