; Auto-generated. Do not edit!


(cl:in-package aquacore-msg)


;//! \htmlinclude SwimForwardActionGoal.msg.html

(cl:defclass <SwimForwardActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type aquacore-msg:SwimForwardGoal
    :initform (cl:make-instance 'aquacore-msg:SwimForwardGoal)))
)

(cl:defclass SwimForwardActionGoal (<SwimForwardActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SwimForwardActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SwimForwardActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name aquacore-msg:<SwimForwardActionGoal> is deprecated: use aquacore-msg:SwimForwardActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <SwimForwardActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader aquacore-msg:header-val is deprecated.  Use aquacore-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <SwimForwardActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader aquacore-msg:goal_id-val is deprecated.  Use aquacore-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <SwimForwardActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader aquacore-msg:goal-val is deprecated.  Use aquacore-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SwimForwardActionGoal>) ostream)
  "Serializes a message object of type '<SwimForwardActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SwimForwardActionGoal>) istream)
  "Deserializes a message object of type '<SwimForwardActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SwimForwardActionGoal>)))
  "Returns string type for a message object of type '<SwimForwardActionGoal>"
  "aquacore/SwimForwardActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SwimForwardActionGoal)))
  "Returns string type for a message object of type 'SwimForwardActionGoal"
  "aquacore/SwimForwardActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SwimForwardActionGoal>)))
  "Returns md5sum for a message object of type '<SwimForwardActionGoal>"
  "b588c6db3de822380c09ea3326ae8bbd")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SwimForwardActionGoal)))
  "Returns md5sum for a message object of type 'SwimForwardActionGoal"
  "b588c6db3de822380c09ea3326ae8bbd")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SwimForwardActionGoal>)))
  "Returns full string definition for message of type '<SwimForwardActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%SwimForwardGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: aquacore/SwimForwardGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# BIG WARNING!!! It is potentially misleading that at the beginning the robot will turn~%#                to the target yaw, and then swim straight from that point onwards.  ~%~%# Desired Goal~%float64 duration     # in s~%float64 speed        # in pseudo-unit-rate~%float32 target_depth # in m; set to -1 to use robot's current depth~%float32 target_yaw   # in deg; set to 361 to use robot's current yaw~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SwimForwardActionGoal)))
  "Returns full string definition for message of type 'SwimForwardActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%SwimForwardGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%# 0: no frame~%# 1: global frame~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: aquacore/SwimForwardGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# BIG WARNING!!! It is potentially misleading that at the beginning the robot will turn~%#                to the target yaw, and then swim straight from that point onwards.  ~%~%# Desired Goal~%float64 duration     # in s~%float64 speed        # in pseudo-unit-rate~%float32 target_depth # in m; set to -1 to use robot's current depth~%float32 target_yaw   # in deg; set to 361 to use robot's current yaw~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SwimForwardActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SwimForwardActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'SwimForwardActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
