; Auto-generated. Do not edit!


(cl:in-package aquacore-msg)


;//! \htmlinclude SwimForwardFeedback.msg.html

(cl:defclass <SwimForwardFeedback> (roslisp-msg-protocol:ros-message)
  ((percent_time_completed
    :reader percent_time_completed
    :initarg :percent_time_completed
    :type cl:float
    :initform 0.0))
)

(cl:defclass SwimForwardFeedback (<SwimForwardFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <SwimForwardFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'SwimForwardFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name aquacore-msg:<SwimForwardFeedback> is deprecated: use aquacore-msg:SwimForwardFeedback instead.")))

(cl:ensure-generic-function 'percent_time_completed-val :lambda-list '(m))
(cl:defmethod percent_time_completed-val ((m <SwimForwardFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader aquacore-msg:percent_time_completed-val is deprecated.  Use aquacore-msg:percent_time_completed instead.")
  (percent_time_completed m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <SwimForwardFeedback>) ostream)
  "Serializes a message object of type '<SwimForwardFeedback>"
  (cl:let ((bits (roslisp-utils:encode-double-float-bits (cl:slot-value msg 'percent_time_completed))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <SwimForwardFeedback>) istream)
  "Deserializes a message object of type '<SwimForwardFeedback>"
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:slot-value msg 'percent_time_completed) (roslisp-utils:decode-double-float-bits bits)))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<SwimForwardFeedback>)))
  "Returns string type for a message object of type '<SwimForwardFeedback>"
  "aquacore/SwimForwardFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'SwimForwardFeedback)))
  "Returns string type for a message object of type 'SwimForwardFeedback"
  "aquacore/SwimForwardFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<SwimForwardFeedback>)))
  "Returns md5sum for a message object of type '<SwimForwardFeedback>"
  "e5d72683b5876219c47676683509ce7c")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'SwimForwardFeedback)))
  "Returns md5sum for a message object of type 'SwimForwardFeedback"
  "e5d72683b5876219c47676683509ce7c")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<SwimForwardFeedback>)))
  "Returns full string definition for message of type '<SwimForwardFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# Feedback~%float64 percent_time_completed~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'SwimForwardFeedback)))
  "Returns full string definition for message of type 'SwimForwardFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%# Feedback~%float64 percent_time_completed~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <SwimForwardFeedback>))
  (cl:+ 0
     8
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <SwimForwardFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'SwimForwardFeedback
    (cl:cons ':percent_time_completed (percent_time_completed msg))
))
