// Generated by gencpp from file aquajoy/UpdateAquaTeleopJoyParams.msg
// DO NOT EDIT!


#ifndef AQUAJOY_MESSAGE_UPDATEAQUATELEOPJOYPARAMS_H
#define AQUAJOY_MESSAGE_UPDATEAQUATELEOPJOYPARAMS_H

#include <ros/service_traits.h>


#include <aquajoy/UpdateAquaTeleopJoyParamsRequest.h>
#include <aquajoy/UpdateAquaTeleopJoyParamsResponse.h>


namespace aquajoy
{

struct UpdateAquaTeleopJoyParams
{

typedef UpdateAquaTeleopJoyParamsRequest Request;
typedef UpdateAquaTeleopJoyParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct UpdateAquaTeleopJoyParams
} // namespace aquajoy


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aquajoy::UpdateAquaTeleopJoyParams > {
  static const char* value()
  {
    return "1e83859aeb42bc42c7f92e0fd76391e7";
  }

  static const char* value(const ::aquajoy::UpdateAquaTeleopJoyParams&) { return value(); }
};

template<>
struct DataType< ::aquajoy::UpdateAquaTeleopJoyParams > {
  static const char* value()
  {
    return "aquajoy/UpdateAquaTeleopJoyParams";
  }

  static const char* value(const ::aquajoy::UpdateAquaTeleopJoyParams&) { return value(); }
};


// service_traits::MD5Sum< ::aquajoy::UpdateAquaTeleopJoyParamsRequest> should match 
// service_traits::MD5Sum< ::aquajoy::UpdateAquaTeleopJoyParams > 
template<>
struct MD5Sum< ::aquajoy::UpdateAquaTeleopJoyParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aquajoy::UpdateAquaTeleopJoyParams >::value();
  }
  static const char* value(const ::aquajoy::UpdateAquaTeleopJoyParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquajoy::UpdateAquaTeleopJoyParamsRequest> should match 
// service_traits::DataType< ::aquajoy::UpdateAquaTeleopJoyParams > 
template<>
struct DataType< ::aquajoy::UpdateAquaTeleopJoyParamsRequest>
{
  static const char* value()
  {
    return DataType< ::aquajoy::UpdateAquaTeleopJoyParams >::value();
  }
  static const char* value(const ::aquajoy::UpdateAquaTeleopJoyParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aquajoy::UpdateAquaTeleopJoyParamsResponse> should match 
// service_traits::MD5Sum< ::aquajoy::UpdateAquaTeleopJoyParams > 
template<>
struct MD5Sum< ::aquajoy::UpdateAquaTeleopJoyParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aquajoy::UpdateAquaTeleopJoyParams >::value();
  }
  static const char* value(const ::aquajoy::UpdateAquaTeleopJoyParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquajoy::UpdateAquaTeleopJoyParamsResponse> should match 
// service_traits::DataType< ::aquajoy::UpdateAquaTeleopJoyParams > 
template<>
struct DataType< ::aquajoy::UpdateAquaTeleopJoyParamsResponse>
{
  static const char* value()
  {
    return DataType< ::aquajoy::UpdateAquaTeleopJoyParams >::value();
  }
  static const char* value(const ::aquajoy::UpdateAquaTeleopJoyParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AQUAJOY_MESSAGE_UPDATEAQUATELEOPJOYPARAMS_H
