// Generated by gencpp from file aquacore/ChangeDepthGoal.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_CHANGEDEPTHGOAL_H
#define AQUACORE_MESSAGE_CHANGEDEPTHGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aquacore
{
template <class ContainerAllocator>
struct ChangeDepthGoal_
{
  typedef ChangeDepthGoal_<ContainerAllocator> Type;

  ChangeDepthGoal_()
    : depth(0.0)
    , speed(0.0)  {
    }
  ChangeDepthGoal_(const ContainerAllocator& _alloc)
    : depth(0.0)
    , speed(0.0)  {
    }



   typedef float _depth_type;
  _depth_type depth;

   typedef double _speed_type;
  _speed_type speed;




  typedef boost::shared_ptr< ::aquacore::ChangeDepthGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aquacore::ChangeDepthGoal_<ContainerAllocator> const> ConstPtr;

}; // struct ChangeDepthGoal_

typedef ::aquacore::ChangeDepthGoal_<std::allocator<void> > ChangeDepthGoal;

typedef boost::shared_ptr< ::aquacore::ChangeDepthGoal > ChangeDepthGoalPtr;
typedef boost::shared_ptr< ::aquacore::ChangeDepthGoal const> ChangeDepthGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aquacore::ChangeDepthGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aquacore::ChangeDepthGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aquacore

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'aquacore': ['/home/2014/tko4/robotAss1/src/aquacore/msg', '/home/2014/tko4/robotAss1/devel/share/aquacore/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aquacore::ChangeDepthGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aquacore::ChangeDepthGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aquacore::ChangeDepthGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aquacore::ChangeDepthGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aquacore::ChangeDepthGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aquacore::ChangeDepthGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aquacore::ChangeDepthGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "4c547ce0c0ba6eb4d0a01719590b156a";
  }

  static const char* value(const ::aquacore::ChangeDepthGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x4c547ce0c0ba6eb4ULL;
  static const uint64_t static_value2 = 0xd0a01719590b156aULL;
};

template<class ContainerAllocator>
struct DataType< ::aquacore::ChangeDepthGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aquacore/ChangeDepthGoal";
  }

  static const char* value(const ::aquacore::ChangeDepthGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aquacore::ChangeDepthGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Desired Goal\n\
float32 depth # in m (be weary of depth sensor's constant depth offset)\n\
float64 speed # in m/s (using depth autopilot) or pseudo-unit-rate (using angles autopilot)\n\
\n\
";
  }

  static const char* value(const ::aquacore::ChangeDepthGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aquacore::ChangeDepthGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.depth);
      stream.next(m.speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct ChangeDepthGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aquacore::ChangeDepthGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aquacore::ChangeDepthGoal_<ContainerAllocator>& v)
  {
    s << indent << "depth: ";
    Printer<float>::stream(s, indent + "  ", v.depth);
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AQUACORE_MESSAGE_CHANGEDEPTHGOAL_H
