// Generated by gencpp from file aquacore/DoSurfaceTaskGoal.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_DOSURFACETASKGOAL_H
#define AQUACORE_MESSAGE_DOSURFACETASKGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aquacore
{
template <class ContainerAllocator>
struct DoSurfaceTaskGoal_
{
  typedef DoSurfaceTaskGoal_<ContainerAllocator> Type;

  DoSurfaceTaskGoal_()
    : task(0)
    , ascend_speed(0.0)  {
    }
  DoSurfaceTaskGoal_(const ContainerAllocator& _alloc)
    : task(0)
    , ascend_speed(0.0)  {
    }



   typedef int8_t _task_type;
  _task_type task;

   typedef double _ascend_speed_type;
  _ascend_speed_type ascend_speed;




  typedef boost::shared_ptr< ::aquacore::DoSurfaceTaskGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aquacore::DoSurfaceTaskGoal_<ContainerAllocator> const> ConstPtr;

}; // struct DoSurfaceTaskGoal_

typedef ::aquacore::DoSurfaceTaskGoal_<std::allocator<void> > DoSurfaceTaskGoal;

typedef boost::shared_ptr< ::aquacore::DoSurfaceTaskGoal > DoSurfaceTaskGoalPtr;
typedef boost::shared_ptr< ::aquacore::DoSurfaceTaskGoal const> DoSurfaceTaskGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aquacore::DoSurfaceTaskGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aquacore::DoSurfaceTaskGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aquacore

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'aquacore': ['/home/2014/tko4/robotAss1/src/aquacore/msg', '/home/2014/tko4/robotAss1/devel/share/aquacore/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aquacore::DoSurfaceTaskGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aquacore::DoSurfaceTaskGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aquacore::DoSurfaceTaskGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aquacore::DoSurfaceTaskGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aquacore::DoSurfaceTaskGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aquacore::DoSurfaceTaskGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aquacore::DoSurfaceTaskGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "182b1839eeeb8a6283216175bc34cfac";
  }

  static const char* value(const ::aquacore::DoSurfaceTaskGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x182b1839eeeb8a62ULL;
  static const uint64_t static_value2 = 0x83216175bc34cfacULL;
};

template<class ContainerAllocator>
struct DataType< ::aquacore::DoSurfaceTaskGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aquacore/DoSurfaceTaskGoal";
  }

  static const char* value(const ::aquacore::DoSurfaceTaskGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aquacore::DoSurfaceTaskGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# Desired Goal\n\
byte task                                # see SurfaceTaskTypes.msg\n\
float64 ascend_speed                     # in m/s (using depth autopilot) or pseudo-unit-rate (using angles autopilot)\n\
\n\
";
  }

  static const char* value(const ::aquacore::DoSurfaceTaskGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aquacore::DoSurfaceTaskGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.task);
      stream.next(m.ascend_speed);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct DoSurfaceTaskGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aquacore::DoSurfaceTaskGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aquacore::DoSurfaceTaskGoal_<ContainerAllocator>& v)
  {
    s << indent << "task: ";
    Printer<int8_t>::stream(s, indent + "  ", v.task);
    s << indent << "ascend_speed: ";
    Printer<double>::stream(s, indent + "  ", v.ascend_speed);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AQUACORE_MESSAGE_DOSURFACETASKGOAL_H
