// Generated by gencpp from file aquacore/DumpAllVars.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_DUMPALLVARS_H
#define AQUACORE_MESSAGE_DUMPALLVARS_H

#include <ros/service_traits.h>


#include <aquacore/DumpAllVarsRequest.h>
#include <aquacore/DumpAllVarsResponse.h>


namespace aquacore
{

struct DumpAllVars
{

typedef DumpAllVarsRequest Request;
typedef DumpAllVarsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct DumpAllVars
} // namespace aquacore


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aquacore::DumpAllVars > {
  static const char* value()
  {
    return "0a763daf42d6252113b71c689c9e864f";
  }

  static const char* value(const ::aquacore::DumpAllVars&) { return value(); }
};

template<>
struct DataType< ::aquacore::DumpAllVars > {
  static const char* value()
  {
    return "aquacore/DumpAllVars";
  }

  static const char* value(const ::aquacore::DumpAllVars&) { return value(); }
};


// service_traits::MD5Sum< ::aquacore::DumpAllVarsRequest> should match 
// service_traits::MD5Sum< ::aquacore::DumpAllVars > 
template<>
struct MD5Sum< ::aquacore::DumpAllVarsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::DumpAllVars >::value();
  }
  static const char* value(const ::aquacore::DumpAllVarsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::DumpAllVarsRequest> should match 
// service_traits::DataType< ::aquacore::DumpAllVars > 
template<>
struct DataType< ::aquacore::DumpAllVarsRequest>
{
  static const char* value()
  {
    return DataType< ::aquacore::DumpAllVars >::value();
  }
  static const char* value(const ::aquacore::DumpAllVarsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aquacore::DumpAllVarsResponse> should match 
// service_traits::MD5Sum< ::aquacore::DumpAllVars > 
template<>
struct MD5Sum< ::aquacore::DumpAllVarsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::DumpAllVars >::value();
  }
  static const char* value(const ::aquacore::DumpAllVarsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::DumpAllVarsResponse> should match 
// service_traits::DataType< ::aquacore::DumpAllVars > 
template<>
struct DataType< ::aquacore::DumpAllVarsResponse>
{
  static const char* value()
  {
    return DataType< ::aquacore::DumpAllVars >::value();
  }
  static const char* value(const ::aquacore::DumpAllVarsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AQUACORE_MESSAGE_DUMPALLVARS_H
