// Generated by gencpp from file aquacore/EmptyBool.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_EMPTYBOOL_H
#define AQUACORE_MESSAGE_EMPTYBOOL_H

#include <ros/service_traits.h>


#include <aquacore/EmptyBoolRequest.h>
#include <aquacore/EmptyBoolResponse.h>


namespace aquacore
{

struct EmptyBool
{

typedef EmptyBoolRequest Request;
typedef EmptyBoolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EmptyBool
} // namespace aquacore


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aquacore::EmptyBool > {
  static const char* value()
  {
    return "eb13ac1f1354ccecb7941ee8fa2192e8";
  }

  static const char* value(const ::aquacore::EmptyBool&) { return value(); }
};

template<>
struct DataType< ::aquacore::EmptyBool > {
  static const char* value()
  {
    return "aquacore/EmptyBool";
  }

  static const char* value(const ::aquacore::EmptyBool&) { return value(); }
};


// service_traits::MD5Sum< ::aquacore::EmptyBoolRequest> should match 
// service_traits::MD5Sum< ::aquacore::EmptyBool > 
template<>
struct MD5Sum< ::aquacore::EmptyBoolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::EmptyBool >::value();
  }
  static const char* value(const ::aquacore::EmptyBoolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::EmptyBoolRequest> should match 
// service_traits::DataType< ::aquacore::EmptyBool > 
template<>
struct DataType< ::aquacore::EmptyBoolRequest>
{
  static const char* value()
  {
    return DataType< ::aquacore::EmptyBool >::value();
  }
  static const char* value(const ::aquacore::EmptyBoolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aquacore::EmptyBoolResponse> should match 
// service_traits::MD5Sum< ::aquacore::EmptyBool > 
template<>
struct MD5Sum< ::aquacore::EmptyBoolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::EmptyBool >::value();
  }
  static const char* value(const ::aquacore::EmptyBoolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::EmptyBoolResponse> should match 
// service_traits::DataType< ::aquacore::EmptyBool > 
template<>
struct DataType< ::aquacore::EmptyBoolResponse>
{
  static const char* value()
  {
    return DataType< ::aquacore::EmptyBool >::value();
  }
  static const char* value(const ::aquacore::EmptyBoolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AQUACORE_MESSAGE_EMPTYBOOL_H
