// Generated by gencpp from file aquacore/EnableAutopilot.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_ENABLEAUTOPILOT_H
#define AQUACORE_MESSAGE_ENABLEAUTOPILOT_H

#include <ros/service_traits.h>


#include <aquacore/EnableAutopilotRequest.h>
#include <aquacore/EnableAutopilotResponse.h>


namespace aquacore
{

struct EnableAutopilot
{

typedef EnableAutopilotRequest Request;
typedef EnableAutopilotResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EnableAutopilot
} // namespace aquacore


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aquacore::EnableAutopilot > {
  static const char* value()
  {
    return "8ae95d1385d7365f05201d22aea7ac68";
  }

  static const char* value(const ::aquacore::EnableAutopilot&) { return value(); }
};

template<>
struct DataType< ::aquacore::EnableAutopilot > {
  static const char* value()
  {
    return "aquacore/EnableAutopilot";
  }

  static const char* value(const ::aquacore::EnableAutopilot&) { return value(); }
};


// service_traits::MD5Sum< ::aquacore::EnableAutopilotRequest> should match 
// service_traits::MD5Sum< ::aquacore::EnableAutopilot > 
template<>
struct MD5Sum< ::aquacore::EnableAutopilotRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::EnableAutopilot >::value();
  }
  static const char* value(const ::aquacore::EnableAutopilotRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::EnableAutopilotRequest> should match 
// service_traits::DataType< ::aquacore::EnableAutopilot > 
template<>
struct DataType< ::aquacore::EnableAutopilotRequest>
{
  static const char* value()
  {
    return DataType< ::aquacore::EnableAutopilot >::value();
  }
  static const char* value(const ::aquacore::EnableAutopilotRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aquacore::EnableAutopilotResponse> should match 
// service_traits::MD5Sum< ::aquacore::EnableAutopilot > 
template<>
struct MD5Sum< ::aquacore::EnableAutopilotResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::EnableAutopilot >::value();
  }
  static const char* value(const ::aquacore::EnableAutopilotResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::EnableAutopilotResponse> should match 
// service_traits::DataType< ::aquacore::EnableAutopilot > 
template<>
struct DataType< ::aquacore::EnableAutopilotResponse>
{
  static const char* value()
  {
    return DataType< ::aquacore::EnableAutopilot >::value();
  }
  static const char* value(const ::aquacore::EnableAutopilotResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AQUACORE_MESSAGE_ENABLEAUTOPILOT_H
