// Generated by gencpp from file aquacore/EnableDepthControl.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_ENABLEDEPTHCONTROL_H
#define AQUACORE_MESSAGE_ENABLEDEPTHCONTROL_H

#include <ros/service_traits.h>


#include <aquacore/EnableDepthControlRequest.h>
#include <aquacore/EnableDepthControlResponse.h>


namespace aquacore
{

struct EnableDepthControl
{

typedef EnableDepthControlRequest Request;
typedef EnableDepthControlResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EnableDepthControl
} // namespace aquacore


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aquacore::EnableDepthControl > {
  static const char* value()
  {
    return "8ae95d1385d7365f05201d22aea7ac68";
  }

  static const char* value(const ::aquacore::EnableDepthControl&) { return value(); }
};

template<>
struct DataType< ::aquacore::EnableDepthControl > {
  static const char* value()
  {
    return "aquacore/EnableDepthControl";
  }

  static const char* value(const ::aquacore::EnableDepthControl&) { return value(); }
};


// service_traits::MD5Sum< ::aquacore::EnableDepthControlRequest> should match 
// service_traits::MD5Sum< ::aquacore::EnableDepthControl > 
template<>
struct MD5Sum< ::aquacore::EnableDepthControlRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::EnableDepthControl >::value();
  }
  static const char* value(const ::aquacore::EnableDepthControlRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::EnableDepthControlRequest> should match 
// service_traits::DataType< ::aquacore::EnableDepthControl > 
template<>
struct DataType< ::aquacore::EnableDepthControlRequest>
{
  static const char* value()
  {
    return DataType< ::aquacore::EnableDepthControl >::value();
  }
  static const char* value(const ::aquacore::EnableDepthControlRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aquacore::EnableDepthControlResponse> should match 
// service_traits::MD5Sum< ::aquacore::EnableDepthControl > 
template<>
struct MD5Sum< ::aquacore::EnableDepthControlResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::EnableDepthControl >::value();
  }
  static const char* value(const ::aquacore::EnableDepthControlResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::EnableDepthControlResponse> should match 
// service_traits::DataType< ::aquacore::EnableDepthControl > 
template<>
struct DataType< ::aquacore::EnableDepthControlResponse>
{
  static const char* value()
  {
    return DataType< ::aquacore::EnableDepthControl >::value();
  }
  static const char* value(const ::aquacore::EnableDepthControlResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AQUACORE_MESSAGE_ENABLEDEPTHCONTROL_H
