// Generated by gencpp from file aquacore/GetAutopilotState.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_GETAUTOPILOTSTATE_H
#define AQUACORE_MESSAGE_GETAUTOPILOTSTATE_H

#include <ros/service_traits.h>


#include <aquacore/GetAutopilotStateRequest.h>
#include <aquacore/GetAutopilotStateResponse.h>


namespace aquacore
{

struct GetAutopilotState
{

typedef GetAutopilotStateRequest Request;
typedef GetAutopilotStateResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetAutopilotState
} // namespace aquacore


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aquacore::GetAutopilotState > {
  static const char* value()
  {
    return "8c8eeaafe647710bb35d5cfef6b22f76";
  }

  static const char* value(const ::aquacore::GetAutopilotState&) { return value(); }
};

template<>
struct DataType< ::aquacore::GetAutopilotState > {
  static const char* value()
  {
    return "aquacore/GetAutopilotState";
  }

  static const char* value(const ::aquacore::GetAutopilotState&) { return value(); }
};


// service_traits::MD5Sum< ::aquacore::GetAutopilotStateRequest> should match 
// service_traits::MD5Sum< ::aquacore::GetAutopilotState > 
template<>
struct MD5Sum< ::aquacore::GetAutopilotStateRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::GetAutopilotState >::value();
  }
  static const char* value(const ::aquacore::GetAutopilotStateRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::GetAutopilotStateRequest> should match 
// service_traits::DataType< ::aquacore::GetAutopilotState > 
template<>
struct DataType< ::aquacore::GetAutopilotStateRequest>
{
  static const char* value()
  {
    return DataType< ::aquacore::GetAutopilotState >::value();
  }
  static const char* value(const ::aquacore::GetAutopilotStateRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aquacore::GetAutopilotStateResponse> should match 
// service_traits::MD5Sum< ::aquacore::GetAutopilotState > 
template<>
struct MD5Sum< ::aquacore::GetAutopilotStateResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::GetAutopilotState >::value();
  }
  static const char* value(const ::aquacore::GetAutopilotStateResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::GetAutopilotStateResponse> should match 
// service_traits::DataType< ::aquacore::GetAutopilotState > 
template<>
struct DataType< ::aquacore::GetAutopilotStateResponse>
{
  static const char* value()
  {
    return DataType< ::aquacore::GetAutopilotState >::value();
  }
  static const char* value(const ::aquacore::GetAutopilotStateResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AQUACORE_MESSAGE_GETAUTOPILOTSTATE_H
