// Generated by gencpp from file aquacore/GetAutopilotParams.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_GETAUTOPILOTPARAMS_H
#define AQUACORE_MESSAGE_GETAUTOPILOTPARAMS_H

#include <ros/service_traits.h>


#include <aquacore/GetAutopilotParamsRequest.h>
#include <aquacore/GetAutopilotParamsResponse.h>


namespace aquacore
{

struct GetAutopilotParams
{

typedef GetAutopilotParamsRequest Request;
typedef GetAutopilotParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetAutopilotParams
} // namespace aquacore


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aquacore::GetAutopilotParams > {
  static const char* value()
  {
    return "8e22f8c3368a715022fd214d9775704d";
  }

  static const char* value(const ::aquacore::GetAutopilotParams&) { return value(); }
};

template<>
struct DataType< ::aquacore::GetAutopilotParams > {
  static const char* value()
  {
    return "aquacore/GetAutopilotParams";
  }

  static const char* value(const ::aquacore::GetAutopilotParams&) { return value(); }
};


// service_traits::MD5Sum< ::aquacore::GetAutopilotParamsRequest> should match 
// service_traits::MD5Sum< ::aquacore::GetAutopilotParams > 
template<>
struct MD5Sum< ::aquacore::GetAutopilotParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::GetAutopilotParams >::value();
  }
  static const char* value(const ::aquacore::GetAutopilotParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::GetAutopilotParamsRequest> should match 
// service_traits::DataType< ::aquacore::GetAutopilotParams > 
template<>
struct DataType< ::aquacore::GetAutopilotParamsRequest>
{
  static const char* value()
  {
    return DataType< ::aquacore::GetAutopilotParams >::value();
  }
  static const char* value(const ::aquacore::GetAutopilotParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aquacore::GetAutopilotParamsResponse> should match 
// service_traits::MD5Sum< ::aquacore::GetAutopilotParams > 
template<>
struct MD5Sum< ::aquacore::GetAutopilotParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::GetAutopilotParams >::value();
  }
  static const char* value(const ::aquacore::GetAutopilotParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::GetAutopilotParamsResponse> should match 
// service_traits::DataType< ::aquacore::GetAutopilotParams > 
template<>
struct DataType< ::aquacore::GetAutopilotParamsResponse>
{
  static const char* value()
  {
    return DataType< ::aquacore::GetAutopilotParams >::value();
  }
  static const char* value(const ::aquacore::GetAutopilotParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AQUACORE_MESSAGE_GETAUTOPILOTPARAMS_H
