// Generated by gencpp from file aquacore/GetLegParams.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_GETLEGPARAMS_H
#define AQUACORE_MESSAGE_GETLEGPARAMS_H

#include <ros/service_traits.h>


#include <aquacore/GetLegParamsRequest.h>
#include <aquacore/GetLegParamsResponse.h>


namespace aquacore
{

struct GetLegParams
{

typedef GetLegParamsRequest Request;
typedef GetLegParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetLegParams
} // namespace aquacore


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aquacore::GetLegParams > {
  static const char* value()
  {
    return "1792bf569e4223f89286c37967c01dcf";
  }

  static const char* value(const ::aquacore::GetLegParams&) { return value(); }
};

template<>
struct DataType< ::aquacore::GetLegParams > {
  static const char* value()
  {
    return "aquacore/GetLegParams";
  }

  static const char* value(const ::aquacore::GetLegParams&) { return value(); }
};


// service_traits::MD5Sum< ::aquacore::GetLegParamsRequest> should match 
// service_traits::MD5Sum< ::aquacore::GetLegParams > 
template<>
struct MD5Sum< ::aquacore::GetLegParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::GetLegParams >::value();
  }
  static const char* value(const ::aquacore::GetLegParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::GetLegParamsRequest> should match 
// service_traits::DataType< ::aquacore::GetLegParams > 
template<>
struct DataType< ::aquacore::GetLegParamsRequest>
{
  static const char* value()
  {
    return DataType< ::aquacore::GetLegParams >::value();
  }
  static const char* value(const ::aquacore::GetLegParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aquacore::GetLegParamsResponse> should match 
// service_traits::MD5Sum< ::aquacore::GetLegParams > 
template<>
struct MD5Sum< ::aquacore::GetLegParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::GetLegParams >::value();
  }
  static const char* value(const ::aquacore::GetLegParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::GetLegParamsResponse> should match 
// service_traits::DataType< ::aquacore::GetLegParams > 
template<>
struct DataType< ::aquacore::GetLegParamsResponse>
{
  static const char* value()
  {
    return DataType< ::aquacore::GetLegParams >::value();
  }
  static const char* value(const ::aquacore::GetLegParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AQUACORE_MESSAGE_GETLEGPARAMS_H
