// Generated by gencpp from file aquacore/GetNamedFloat.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_GETNAMEDFLOAT_H
#define AQUACORE_MESSAGE_GETNAMEDFLOAT_H

#include <ros/service_traits.h>


#include <aquacore/GetNamedFloatRequest.h>
#include <aquacore/GetNamedFloatResponse.h>


namespace aquacore
{

struct GetNamedFloat
{

typedef GetNamedFloatRequest Request;
typedef GetNamedFloatResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetNamedFloat
} // namespace aquacore


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aquacore::GetNamedFloat > {
  static const char* value()
  {
    return "cab3e232f5ab7d227b43ff1e2453857d";
  }

  static const char* value(const ::aquacore::GetNamedFloat&) { return value(); }
};

template<>
struct DataType< ::aquacore::GetNamedFloat > {
  static const char* value()
  {
    return "aquacore/GetNamedFloat";
  }

  static const char* value(const ::aquacore::GetNamedFloat&) { return value(); }
};


// service_traits::MD5Sum< ::aquacore::GetNamedFloatRequest> should match 
// service_traits::MD5Sum< ::aquacore::GetNamedFloat > 
template<>
struct MD5Sum< ::aquacore::GetNamedFloatRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::GetNamedFloat >::value();
  }
  static const char* value(const ::aquacore::GetNamedFloatRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::GetNamedFloatRequest> should match 
// service_traits::DataType< ::aquacore::GetNamedFloat > 
template<>
struct DataType< ::aquacore::GetNamedFloatRequest>
{
  static const char* value()
  {
    return DataType< ::aquacore::GetNamedFloat >::value();
  }
  static const char* value(const ::aquacore::GetNamedFloatRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aquacore::GetNamedFloatResponse> should match 
// service_traits::MD5Sum< ::aquacore::GetNamedFloat > 
template<>
struct MD5Sum< ::aquacore::GetNamedFloatResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::GetNamedFloat >::value();
  }
  static const char* value(const ::aquacore::GetNamedFloatResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::GetNamedFloatResponse> should match 
// service_traits::DataType< ::aquacore::GetNamedFloat > 
template<>
struct DataType< ::aquacore::GetNamedFloatResponse>
{
  static const char* value()
  {
    return DataType< ::aquacore::GetNamedFloat >::value();
  }
  static const char* value(const ::aquacore::GetNamedFloatResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AQUACORE_MESSAGE_GETNAMEDFLOAT_H
