// Generated by gencpp from file aquacore/GetNamedInt.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_GETNAMEDINT_H
#define AQUACORE_MESSAGE_GETNAMEDINT_H

#include <ros/service_traits.h>


#include <aquacore/GetNamedIntRequest.h>
#include <aquacore/GetNamedIntResponse.h>


namespace aquacore
{

struct GetNamedInt
{

typedef GetNamedIntRequest Request;
typedef GetNamedIntResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetNamedInt
} // namespace aquacore


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aquacore::GetNamedInt > {
  static const char* value()
  {
    return "2322c7c7ab60b6436d5b3b659c10095f";
  }

  static const char* value(const ::aquacore::GetNamedInt&) { return value(); }
};

template<>
struct DataType< ::aquacore::GetNamedInt > {
  static const char* value()
  {
    return "aquacore/GetNamedInt";
  }

  static const char* value(const ::aquacore::GetNamedInt&) { return value(); }
};


// service_traits::MD5Sum< ::aquacore::GetNamedIntRequest> should match 
// service_traits::MD5Sum< ::aquacore::GetNamedInt > 
template<>
struct MD5Sum< ::aquacore::GetNamedIntRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::GetNamedInt >::value();
  }
  static const char* value(const ::aquacore::GetNamedIntRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::GetNamedIntRequest> should match 
// service_traits::DataType< ::aquacore::GetNamedInt > 
template<>
struct DataType< ::aquacore::GetNamedIntRequest>
{
  static const char* value()
  {
    return DataType< ::aquacore::GetNamedInt >::value();
  }
  static const char* value(const ::aquacore::GetNamedIntRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aquacore::GetNamedIntResponse> should match 
// service_traits::MD5Sum< ::aquacore::GetNamedInt > 
template<>
struct MD5Sum< ::aquacore::GetNamedIntResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::GetNamedInt >::value();
  }
  static const char* value(const ::aquacore::GetNamedIntResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::GetNamedIntResponse> should match 
// service_traits::DataType< ::aquacore::GetNamedInt > 
template<>
struct DataType< ::aquacore::GetNamedIntResponse>
{
  static const char* value()
  {
    return DataType< ::aquacore::GetNamedInt >::value();
  }
  static const char* value(const ::aquacore::GetNamedIntResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AQUACORE_MESSAGE_GETNAMEDINT_H
