// Generated by gencpp from file aquacore/GetPeriodicLegCommand.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_GETPERIODICLEGCOMMAND_H
#define AQUACORE_MESSAGE_GETPERIODICLEGCOMMAND_H

#include <ros/service_traits.h>


#include <aquacore/GetPeriodicLegCommandRequest.h>
#include <aquacore/GetPeriodicLegCommandResponse.h>


namespace aquacore
{

struct GetPeriodicLegCommand
{

typedef GetPeriodicLegCommandRequest Request;
typedef GetPeriodicLegCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetPeriodicLegCommand
} // namespace aquacore


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aquacore::GetPeriodicLegCommand > {
  static const char* value()
  {
    return "d3befc8a5e5142617cdb8fa5f1aeaff0";
  }

  static const char* value(const ::aquacore::GetPeriodicLegCommand&) { return value(); }
};

template<>
struct DataType< ::aquacore::GetPeriodicLegCommand > {
  static const char* value()
  {
    return "aquacore/GetPeriodicLegCommand";
  }

  static const char* value(const ::aquacore::GetPeriodicLegCommand&) { return value(); }
};


// service_traits::MD5Sum< ::aquacore::GetPeriodicLegCommandRequest> should match 
// service_traits::MD5Sum< ::aquacore::GetPeriodicLegCommand > 
template<>
struct MD5Sum< ::aquacore::GetPeriodicLegCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::GetPeriodicLegCommand >::value();
  }
  static const char* value(const ::aquacore::GetPeriodicLegCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::GetPeriodicLegCommandRequest> should match 
// service_traits::DataType< ::aquacore::GetPeriodicLegCommand > 
template<>
struct DataType< ::aquacore::GetPeriodicLegCommandRequest>
{
  static const char* value()
  {
    return DataType< ::aquacore::GetPeriodicLegCommand >::value();
  }
  static const char* value(const ::aquacore::GetPeriodicLegCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aquacore::GetPeriodicLegCommandResponse> should match 
// service_traits::MD5Sum< ::aquacore::GetPeriodicLegCommand > 
template<>
struct MD5Sum< ::aquacore::GetPeriodicLegCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::GetPeriodicLegCommand >::value();
  }
  static const char* value(const ::aquacore::GetPeriodicLegCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::GetPeriodicLegCommandResponse> should match 
// service_traits::DataType< ::aquacore::GetPeriodicLegCommand > 
template<>
struct DataType< ::aquacore::GetPeriodicLegCommandResponse>
{
  static const char* value()
  {
    return DataType< ::aquacore::GetPeriodicLegCommand >::value();
  }
  static const char* value(const ::aquacore::GetPeriodicLegCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AQUACORE_MESSAGE_GETPERIODICLEGCOMMAND_H
