// Generated by gencpp from file aquacore/GetTargetLegAngles.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_GETTARGETLEGANGLES_H
#define AQUACORE_MESSAGE_GETTARGETLEGANGLES_H

#include <ros/service_traits.h>


#include <aquacore/GetTargetLegAnglesRequest.h>
#include <aquacore/GetTargetLegAnglesResponse.h>


namespace aquacore
{

struct GetTargetLegAngles
{

typedef GetTargetLegAnglesRequest Request;
typedef GetTargetLegAnglesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct GetTargetLegAngles
} // namespace aquacore


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aquacore::GetTargetLegAngles > {
  static const char* value()
  {
    return "0290c096db0f9662921c53f2603ee48a";
  }

  static const char* value(const ::aquacore::GetTargetLegAngles&) { return value(); }
};

template<>
struct DataType< ::aquacore::GetTargetLegAngles > {
  static const char* value()
  {
    return "aquacore/GetTargetLegAngles";
  }

  static const char* value(const ::aquacore::GetTargetLegAngles&) { return value(); }
};


// service_traits::MD5Sum< ::aquacore::GetTargetLegAnglesRequest> should match 
// service_traits::MD5Sum< ::aquacore::GetTargetLegAngles > 
template<>
struct MD5Sum< ::aquacore::GetTargetLegAnglesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::GetTargetLegAngles >::value();
  }
  static const char* value(const ::aquacore::GetTargetLegAnglesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::GetTargetLegAnglesRequest> should match 
// service_traits::DataType< ::aquacore::GetTargetLegAngles > 
template<>
struct DataType< ::aquacore::GetTargetLegAnglesRequest>
{
  static const char* value()
  {
    return DataType< ::aquacore::GetTargetLegAngles >::value();
  }
  static const char* value(const ::aquacore::GetTargetLegAnglesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aquacore::GetTargetLegAnglesResponse> should match 
// service_traits::MD5Sum< ::aquacore::GetTargetLegAngles > 
template<>
struct MD5Sum< ::aquacore::GetTargetLegAnglesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::GetTargetLegAngles >::value();
  }
  static const char* value(const ::aquacore::GetTargetLegAnglesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::GetTargetLegAnglesResponse> should match 
// service_traits::DataType< ::aquacore::GetTargetLegAngles > 
template<>
struct DataType< ::aquacore::GetTargetLegAnglesResponse>
{
  static const char* value()
  {
    return DataType< ::aquacore::GetTargetLegAngles >::value();
  }
  static const char* value(const ::aquacore::GetTargetLegAnglesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AQUACORE_MESSAGE_GETTARGETLEGANGLES_H
