// Generated by gencpp from file aquacore/GotoResult.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_GOTORESULT_H
#define AQUACORE_MESSAGE_GOTORESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aquacore
{
template <class ContainerAllocator>
struct GotoResult_
{
  typedef GotoResult_<ContainerAllocator> Type;

  GotoResult_()
    : arrived_successfully(false)  {
    }
  GotoResult_(const ContainerAllocator& _alloc)
    : arrived_successfully(false)  {
    }



   typedef uint8_t _arrived_successfully_type;
  _arrived_successfully_type arrived_successfully;




  typedef boost::shared_ptr< ::aquacore::GotoResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aquacore::GotoResult_<ContainerAllocator> const> ConstPtr;

}; // struct GotoResult_

typedef ::aquacore::GotoResult_<std::allocator<void> > GotoResult;

typedef boost::shared_ptr< ::aquacore::GotoResult > GotoResultPtr;
typedef boost::shared_ptr< ::aquacore::GotoResult const> GotoResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aquacore::GotoResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aquacore::GotoResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aquacore

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'aquacore': ['/home/2014/tko4/robotAss1/src/aquacore/msg', '/home/2014/tko4/robotAss1/devel/share/aquacore/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aquacore::GotoResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aquacore::GotoResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aquacore::GotoResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aquacore::GotoResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aquacore::GotoResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aquacore::GotoResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aquacore::GotoResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d67e2e7ba3581d5761cc209bedbe1209";
  }

  static const char* value(const ::aquacore::GotoResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd67e2e7ba3581d57ULL;
  static const uint64_t static_value2 = 0x61cc209bedbe1209ULL;
};

template<class ContainerAllocator>
struct DataType< ::aquacore::GotoResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aquacore/GotoResult";
  }

  static const char* value(const ::aquacore::GotoResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aquacore::GotoResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
# Result\n\
\n\
bool arrived_successfully\n\
\n\
";
  }

  static const char* value(const ::aquacore::GotoResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aquacore::GotoResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.arrived_successfully);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct GotoResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aquacore::GotoResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aquacore::GotoResult_<ContainerAllocator>& v)
  {
    s << indent << "arrived_successfully: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.arrived_successfully);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AQUACORE_MESSAGE_GOTORESULT_H
