// Generated by gencpp from file aquacore/GotoFeedback.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_GOTOFEEDBACK_H
#define AQUACORE_MESSAGE_GOTOFEEDBACK_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose.h>

namespace aquacore
{
template <class ContainerAllocator>
struct GotoFeedback_
{
  typedef GotoFeedback_<ContainerAllocator> Type;

  GotoFeedback_()
    : current_waypoint()  {
    }
  GotoFeedback_(const ContainerAllocator& _alloc)
    : current_waypoint(_alloc)  {
    }



   typedef  ::geometry_msgs::Pose_<ContainerAllocator>  _current_waypoint_type;
  _current_waypoint_type current_waypoint;




  typedef boost::shared_ptr< ::aquacore::GotoFeedback_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aquacore::GotoFeedback_<ContainerAllocator> const> ConstPtr;

}; // struct GotoFeedback_

typedef ::aquacore::GotoFeedback_<std::allocator<void> > GotoFeedback;

typedef boost::shared_ptr< ::aquacore::GotoFeedback > GotoFeedbackPtr;
typedef boost::shared_ptr< ::aquacore::GotoFeedback const> GotoFeedbackConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aquacore::GotoFeedback_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aquacore::GotoFeedback_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aquacore

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'aquacore': ['/home/2014/tko4/robotAss1/src/aquacore/msg', '/home/2014/tko4/robotAss1/devel/share/aquacore/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aquacore::GotoFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aquacore::GotoFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aquacore::GotoFeedback_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aquacore::GotoFeedback_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aquacore::GotoFeedback_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aquacore::GotoFeedback_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aquacore::GotoFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1996e7f170eaa92091d553f10efda1ee";
  }

  static const char* value(const ::aquacore::GotoFeedback_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1996e7f170eaa920ULL;
  static const uint64_t static_value2 = 0x91d553f10efda1eeULL;
};

template<class ContainerAllocator>
struct DataType< ::aquacore::GotoFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aquacore/GotoFeedback";
  }

  static const char* value(const ::aquacore::GotoFeedback_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aquacore::GotoFeedback_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
# Feedback \n\
\n\
# Current position and orientation. \n\
# Semantics as above.\n\
geometry_msgs/Pose current_waypoint\n\
\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Pose\n\
# A representation of pose in free space, composed of postion and orientation. \n\
Point position\n\
Quaternion orientation\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Quaternion\n\
# This represents an orientation in free space in quaternion form.\n\
\n\
float64 x\n\
float64 y\n\
float64 z\n\
float64 w\n\
";
  }

  static const char* value(const ::aquacore::GotoFeedback_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aquacore::GotoFeedback_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.current_waypoint);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct GotoFeedback_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aquacore::GotoFeedback_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aquacore::GotoFeedback_<ContainerAllocator>& v)
  {
    s << indent << "current_waypoint: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose_<ContainerAllocator> >::stream(s, indent + "  ", v.current_waypoint);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AQUACORE_MESSAGE_GOTOFEEDBACK_H
