// Generated by gencpp from file aquacore/KeepAlive.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_KEEPALIVE_H
#define AQUACORE_MESSAGE_KEEPALIVE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aquacore
{
template <class ContainerAllocator>
struct KeepAlive_
{
  typedef KeepAlive_<ContainerAllocator> Type;

  KeepAlive_()
    : keepalive(false)  {
    }
  KeepAlive_(const ContainerAllocator& _alloc)
    : keepalive(false)  {
    }



   typedef uint8_t _keepalive_type;
  _keepalive_type keepalive;




  typedef boost::shared_ptr< ::aquacore::KeepAlive_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aquacore::KeepAlive_<ContainerAllocator> const> ConstPtr;

}; // struct KeepAlive_

typedef ::aquacore::KeepAlive_<std::allocator<void> > KeepAlive;

typedef boost::shared_ptr< ::aquacore::KeepAlive > KeepAlivePtr;
typedef boost::shared_ptr< ::aquacore::KeepAlive const> KeepAliveConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aquacore::KeepAlive_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aquacore::KeepAlive_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aquacore

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'aquacore': ['/home/2014/tko4/robotAss1/src/aquacore/msg', '/home/2014/tko4/robotAss1/devel/share/aquacore/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aquacore::KeepAlive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aquacore::KeepAlive_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aquacore::KeepAlive_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aquacore::KeepAlive_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aquacore::KeepAlive_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aquacore::KeepAlive_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aquacore::KeepAlive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "24fb7054ad8b54e70f691c17acc4088d";
  }

  static const char* value(const ::aquacore::KeepAlive_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x24fb7054ad8b54e7ULL;
  static const uint64_t static_value2 = 0x0f691c17acc4088dULL;
};

template<class ContainerAllocator>
struct DataType< ::aquacore::KeepAlive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aquacore/KeepAlive";
  }

  static const char* value(const ::aquacore::KeepAlive_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aquacore::KeepAlive_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bool keepalive\n\
";
  }

  static const char* value(const ::aquacore::KeepAlive_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aquacore::KeepAlive_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.keepalive);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct KeepAlive_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aquacore::KeepAlive_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aquacore::KeepAlive_<ContainerAllocator>& v)
  {
    s << indent << "keepalive: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.keepalive);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AQUACORE_MESSAGE_KEEPALIVE_H
