// Generated by gencpp from file aquacore/Menu.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_MENU_H
#define AQUACORE_MESSAGE_MENU_H

#include <ros/service_traits.h>


#include <aquacore/MenuRequest.h>
#include <aquacore/MenuResponse.h>


namespace aquacore
{

struct Menu
{

typedef MenuRequest Request;
typedef MenuResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct Menu
} // namespace aquacore


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aquacore::Menu > {
  static const char* value()
  {
    return "b6c70a1e971f94500062019a89d5686d";
  }

  static const char* value(const ::aquacore::Menu&) { return value(); }
};

template<>
struct DataType< ::aquacore::Menu > {
  static const char* value()
  {
    return "aquacore/Menu";
  }

  static const char* value(const ::aquacore::Menu&) { return value(); }
};


// service_traits::MD5Sum< ::aquacore::MenuRequest> should match 
// service_traits::MD5Sum< ::aquacore::Menu > 
template<>
struct MD5Sum< ::aquacore::MenuRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::Menu >::value();
  }
  static const char* value(const ::aquacore::MenuRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::MenuRequest> should match 
// service_traits::DataType< ::aquacore::Menu > 
template<>
struct DataType< ::aquacore::MenuRequest>
{
  static const char* value()
  {
    return DataType< ::aquacore::Menu >::value();
  }
  static const char* value(const ::aquacore::MenuRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aquacore::MenuResponse> should match 
// service_traits::MD5Sum< ::aquacore::Menu > 
template<>
struct MD5Sum< ::aquacore::MenuResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::Menu >::value();
  }
  static const char* value(const ::aquacore::MenuResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::MenuResponse> should match 
// service_traits::DataType< ::aquacore::Menu > 
template<>
struct DataType< ::aquacore::MenuResponse>
{
  static const char* value()
  {
    return DataType< ::aquacore::Menu >::value();
  }
  static const char* value(const ::aquacore::MenuResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AQUACORE_MESSAGE_MENU_H
