// Generated by gencpp from file aquacore/RunSimulationUntilTime.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_RUNSIMULATIONUNTILTIME_H
#define AQUACORE_MESSAGE_RUNSIMULATIONUNTILTIME_H

#include <ros/service_traits.h>


#include <aquacore/RunSimulationUntilTimeRequest.h>
#include <aquacore/RunSimulationUntilTimeResponse.h>


namespace aquacore
{

struct RunSimulationUntilTime
{

typedef RunSimulationUntilTimeRequest Request;
typedef RunSimulationUntilTimeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct RunSimulationUntilTime
} // namespace aquacore


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aquacore::RunSimulationUntilTime > {
  static const char* value()
  {
    return "458847662e311d516350b4039d9585f1";
  }

  static const char* value(const ::aquacore::RunSimulationUntilTime&) { return value(); }
};

template<>
struct DataType< ::aquacore::RunSimulationUntilTime > {
  static const char* value()
  {
    return "aquacore/RunSimulationUntilTime";
  }

  static const char* value(const ::aquacore::RunSimulationUntilTime&) { return value(); }
};


// service_traits::MD5Sum< ::aquacore::RunSimulationUntilTimeRequest> should match 
// service_traits::MD5Sum< ::aquacore::RunSimulationUntilTime > 
template<>
struct MD5Sum< ::aquacore::RunSimulationUntilTimeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::RunSimulationUntilTime >::value();
  }
  static const char* value(const ::aquacore::RunSimulationUntilTimeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::RunSimulationUntilTimeRequest> should match 
// service_traits::DataType< ::aquacore::RunSimulationUntilTime > 
template<>
struct DataType< ::aquacore::RunSimulationUntilTimeRequest>
{
  static const char* value()
  {
    return DataType< ::aquacore::RunSimulationUntilTime >::value();
  }
  static const char* value(const ::aquacore::RunSimulationUntilTimeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aquacore::RunSimulationUntilTimeResponse> should match 
// service_traits::MD5Sum< ::aquacore::RunSimulationUntilTime > 
template<>
struct MD5Sum< ::aquacore::RunSimulationUntilTimeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::RunSimulationUntilTime >::value();
  }
  static const char* value(const ::aquacore::RunSimulationUntilTimeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::RunSimulationUntilTimeResponse> should match 
// service_traits::DataType< ::aquacore::RunSimulationUntilTime > 
template<>
struct DataType< ::aquacore::RunSimulationUntilTimeResponse>
{
  static const char* value()
  {
    return DataType< ::aquacore::RunSimulationUntilTime >::value();
  }
  static const char* value(const ::aquacore::RunSimulationUntilTimeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AQUACORE_MESSAGE_RUNSIMULATIONUNTILTIME_H
