// Generated by gencpp from file aquacore/SetAutopilotParams.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_SETAUTOPILOTPARAMS_H
#define AQUACORE_MESSAGE_SETAUTOPILOTPARAMS_H

#include <ros/service_traits.h>


#include <aquacore/SetAutopilotParamsRequest.h>
#include <aquacore/SetAutopilotParamsResponse.h>


namespace aquacore
{

struct SetAutopilotParams
{

typedef SetAutopilotParamsRequest Request;
typedef SetAutopilotParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetAutopilotParams
} // namespace aquacore


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aquacore::SetAutopilotParams > {
  static const char* value()
  {
    return "e2c9c4a808bfa8ef83980bb0222137bf";
  }

  static const char* value(const ::aquacore::SetAutopilotParams&) { return value(); }
};

template<>
struct DataType< ::aquacore::SetAutopilotParams > {
  static const char* value()
  {
    return "aquacore/SetAutopilotParams";
  }

  static const char* value(const ::aquacore::SetAutopilotParams&) { return value(); }
};


// service_traits::MD5Sum< ::aquacore::SetAutopilotParamsRequest> should match 
// service_traits::MD5Sum< ::aquacore::SetAutopilotParams > 
template<>
struct MD5Sum< ::aquacore::SetAutopilotParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::SetAutopilotParams >::value();
  }
  static const char* value(const ::aquacore::SetAutopilotParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::SetAutopilotParamsRequest> should match 
// service_traits::DataType< ::aquacore::SetAutopilotParams > 
template<>
struct DataType< ::aquacore::SetAutopilotParamsRequest>
{
  static const char* value()
  {
    return DataType< ::aquacore::SetAutopilotParams >::value();
  }
  static const char* value(const ::aquacore::SetAutopilotParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aquacore::SetAutopilotParamsResponse> should match 
// service_traits::MD5Sum< ::aquacore::SetAutopilotParams > 
template<>
struct MD5Sum< ::aquacore::SetAutopilotParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::SetAutopilotParams >::value();
  }
  static const char* value(const ::aquacore::SetAutopilotParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::SetAutopilotParamsResponse> should match 
// service_traits::DataType< ::aquacore::SetAutopilotParams > 
template<>
struct DataType< ::aquacore::SetAutopilotParamsResponse>
{
  static const char* value()
  {
    return DataType< ::aquacore::SetAutopilotParams >::value();
  }
  static const char* value(const ::aquacore::SetAutopilotParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AQUACORE_MESSAGE_SETAUTOPILOTPARAMS_H
