// Generated by gencpp from file aquacore/SetAutopilotMode.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_SETAUTOPILOTMODE_H
#define AQUACORE_MESSAGE_SETAUTOPILOTMODE_H

#include <ros/service_traits.h>


#include <aquacore/SetAutopilotModeRequest.h>
#include <aquacore/SetAutopilotModeResponse.h>


namespace aquacore
{

struct SetAutopilotMode
{

typedef SetAutopilotModeRequest Request;
typedef SetAutopilotModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetAutopilotMode
} // namespace aquacore


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aquacore::SetAutopilotMode > {
  static const char* value()
  {
    return "0b08a36ed67e50c96239bec8f215b27f";
  }

  static const char* value(const ::aquacore::SetAutopilotMode&) { return value(); }
};

template<>
struct DataType< ::aquacore::SetAutopilotMode > {
  static const char* value()
  {
    return "aquacore/SetAutopilotMode";
  }

  static const char* value(const ::aquacore::SetAutopilotMode&) { return value(); }
};


// service_traits::MD5Sum< ::aquacore::SetAutopilotModeRequest> should match 
// service_traits::MD5Sum< ::aquacore::SetAutopilotMode > 
template<>
struct MD5Sum< ::aquacore::SetAutopilotModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::SetAutopilotMode >::value();
  }
  static const char* value(const ::aquacore::SetAutopilotModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::SetAutopilotModeRequest> should match 
// service_traits::DataType< ::aquacore::SetAutopilotMode > 
template<>
struct DataType< ::aquacore::SetAutopilotModeRequest>
{
  static const char* value()
  {
    return DataType< ::aquacore::SetAutopilotMode >::value();
  }
  static const char* value(const ::aquacore::SetAutopilotModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aquacore::SetAutopilotModeResponse> should match 
// service_traits::MD5Sum< ::aquacore::SetAutopilotMode > 
template<>
struct MD5Sum< ::aquacore::SetAutopilotModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::SetAutopilotMode >::value();
  }
  static const char* value(const ::aquacore::SetAutopilotModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::SetAutopilotModeResponse> should match 
// service_traits::DataType< ::aquacore::SetAutopilotMode > 
template<>
struct DataType< ::aquacore::SetAutopilotModeResponse>
{
  static const char* value()
  {
    return DataType< ::aquacore::SetAutopilotMode >::value();
  }
  static const char* value(const ::aquacore::SetAutopilotModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AQUACORE_MESSAGE_SETAUTOPILOTMODE_H
