// Generated by gencpp from file aquacore/SetBool.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_SETBOOL_H
#define AQUACORE_MESSAGE_SETBOOL_H

#include <ros/service_traits.h>


#include <aquacore/SetBoolRequest.h>
#include <aquacore/SetBoolResponse.h>


namespace aquacore
{

struct SetBool
{

typedef SetBoolRequest Request;
typedef SetBoolResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetBool
} // namespace aquacore


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aquacore::SetBool > {
  static const char* value()
  {
    return "e431d687bf4b2c65fbd94b12ae0cb5d9";
  }

  static const char* value(const ::aquacore::SetBool&) { return value(); }
};

template<>
struct DataType< ::aquacore::SetBool > {
  static const char* value()
  {
    return "aquacore/SetBool";
  }

  static const char* value(const ::aquacore::SetBool&) { return value(); }
};


// service_traits::MD5Sum< ::aquacore::SetBoolRequest> should match 
// service_traits::MD5Sum< ::aquacore::SetBool > 
template<>
struct MD5Sum< ::aquacore::SetBoolRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::SetBool >::value();
  }
  static const char* value(const ::aquacore::SetBoolRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::SetBoolRequest> should match 
// service_traits::DataType< ::aquacore::SetBool > 
template<>
struct DataType< ::aquacore::SetBoolRequest>
{
  static const char* value()
  {
    return DataType< ::aquacore::SetBool >::value();
  }
  static const char* value(const ::aquacore::SetBoolRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aquacore::SetBoolResponse> should match 
// service_traits::MD5Sum< ::aquacore::SetBool > 
template<>
struct MD5Sum< ::aquacore::SetBoolResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::SetBool >::value();
  }
  static const char* value(const ::aquacore::SetBoolResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::SetBoolResponse> should match 
// service_traits::DataType< ::aquacore::SetBool > 
template<>
struct DataType< ::aquacore::SetBoolResponse>
{
  static const char* value()
  {
    return DataType< ::aquacore::SetBool >::value();
  }
  static const char* value(const ::aquacore::SetBoolResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AQUACORE_MESSAGE_SETBOOL_H
