// Generated by gencpp from file aquacore/SetDirection.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_SETDIRECTION_H
#define AQUACORE_MESSAGE_SETDIRECTION_H

#include <ros/service_traits.h>


#include <aquacore/SetDirectionRequest.h>
#include <aquacore/SetDirectionResponse.h>


namespace aquacore
{

struct SetDirection
{

typedef SetDirectionRequest Request;
typedef SetDirectionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetDirection
} // namespace aquacore


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aquacore::SetDirection > {
  static const char* value()
  {
    return "0fc3bc45e28c68f06921185960eb727c";
  }

  static const char* value(const ::aquacore::SetDirection&) { return value(); }
};

template<>
struct DataType< ::aquacore::SetDirection > {
  static const char* value()
  {
    return "aquacore/SetDirection";
  }

  static const char* value(const ::aquacore::SetDirection&) { return value(); }
};


// service_traits::MD5Sum< ::aquacore::SetDirectionRequest> should match 
// service_traits::MD5Sum< ::aquacore::SetDirection > 
template<>
struct MD5Sum< ::aquacore::SetDirectionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::SetDirection >::value();
  }
  static const char* value(const ::aquacore::SetDirectionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::SetDirectionRequest> should match 
// service_traits::DataType< ::aquacore::SetDirection > 
template<>
struct DataType< ::aquacore::SetDirectionRequest>
{
  static const char* value()
  {
    return DataType< ::aquacore::SetDirection >::value();
  }
  static const char* value(const ::aquacore::SetDirectionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aquacore::SetDirectionResponse> should match 
// service_traits::MD5Sum< ::aquacore::SetDirection > 
template<>
struct MD5Sum< ::aquacore::SetDirectionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::SetDirection >::value();
  }
  static const char* value(const ::aquacore::SetDirectionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::SetDirectionResponse> should match 
// service_traits::DataType< ::aquacore::SetDirection > 
template<>
struct DataType< ::aquacore::SetDirectionResponse>
{
  static const char* value()
  {
    return DataType< ::aquacore::SetDirection >::value();
  }
  static const char* value(const ::aquacore::SetDirectionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AQUACORE_MESSAGE_SETDIRECTION_H
