// Generated by gencpp from file aquacore/SetLegParams.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_SETLEGPARAMS_H
#define AQUACORE_MESSAGE_SETLEGPARAMS_H

#include <ros/service_traits.h>


#include <aquacore/SetLegParamsRequest.h>
#include <aquacore/SetLegParamsResponse.h>


namespace aquacore
{

struct SetLegParams
{

typedef SetLegParamsRequest Request;
typedef SetLegParamsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetLegParams
} // namespace aquacore


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aquacore::SetLegParams > {
  static const char* value()
  {
    return "1792bf569e4223f89286c37967c01dcf";
  }

  static const char* value(const ::aquacore::SetLegParams&) { return value(); }
};

template<>
struct DataType< ::aquacore::SetLegParams > {
  static const char* value()
  {
    return "aquacore/SetLegParams";
  }

  static const char* value(const ::aquacore::SetLegParams&) { return value(); }
};


// service_traits::MD5Sum< ::aquacore::SetLegParamsRequest> should match 
// service_traits::MD5Sum< ::aquacore::SetLegParams > 
template<>
struct MD5Sum< ::aquacore::SetLegParamsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::SetLegParams >::value();
  }
  static const char* value(const ::aquacore::SetLegParamsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::SetLegParamsRequest> should match 
// service_traits::DataType< ::aquacore::SetLegParams > 
template<>
struct DataType< ::aquacore::SetLegParamsRequest>
{
  static const char* value()
  {
    return DataType< ::aquacore::SetLegParams >::value();
  }
  static const char* value(const ::aquacore::SetLegParamsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aquacore::SetLegParamsResponse> should match 
// service_traits::MD5Sum< ::aquacore::SetLegParams > 
template<>
struct MD5Sum< ::aquacore::SetLegParamsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::SetLegParams >::value();
  }
  static const char* value(const ::aquacore::SetLegParamsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::SetLegParamsResponse> should match 
// service_traits::DataType< ::aquacore::SetLegParams > 
template<>
struct DataType< ::aquacore::SetLegParamsResponse>
{
  static const char* value()
  {
    return DataType< ::aquacore::SetLegParams >::value();
  }
  static const char* value(const ::aquacore::SetLegParamsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AQUACORE_MESSAGE_SETLEGPARAMS_H
