// Generated by gencpp from file aquacore/SetNamedFloat.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_SETNAMEDFLOAT_H
#define AQUACORE_MESSAGE_SETNAMEDFLOAT_H

#include <ros/service_traits.h>


#include <aquacore/SetNamedFloatRequest.h>
#include <aquacore/SetNamedFloatResponse.h>


namespace aquacore
{

struct SetNamedFloat
{

typedef SetNamedFloatRequest Request;
typedef SetNamedFloatResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetNamedFloat
} // namespace aquacore


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aquacore::SetNamedFloat > {
  static const char* value()
  {
    return "db3486341a840969e8845548decf6f11";
  }

  static const char* value(const ::aquacore::SetNamedFloat&) { return value(); }
};

template<>
struct DataType< ::aquacore::SetNamedFloat > {
  static const char* value()
  {
    return "aquacore/SetNamedFloat";
  }

  static const char* value(const ::aquacore::SetNamedFloat&) { return value(); }
};


// service_traits::MD5Sum< ::aquacore::SetNamedFloatRequest> should match 
// service_traits::MD5Sum< ::aquacore::SetNamedFloat > 
template<>
struct MD5Sum< ::aquacore::SetNamedFloatRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::SetNamedFloat >::value();
  }
  static const char* value(const ::aquacore::SetNamedFloatRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::SetNamedFloatRequest> should match 
// service_traits::DataType< ::aquacore::SetNamedFloat > 
template<>
struct DataType< ::aquacore::SetNamedFloatRequest>
{
  static const char* value()
  {
    return DataType< ::aquacore::SetNamedFloat >::value();
  }
  static const char* value(const ::aquacore::SetNamedFloatRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aquacore::SetNamedFloatResponse> should match 
// service_traits::MD5Sum< ::aquacore::SetNamedFloat > 
template<>
struct MD5Sum< ::aquacore::SetNamedFloatResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::SetNamedFloat >::value();
  }
  static const char* value(const ::aquacore::SetNamedFloatResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::SetNamedFloatResponse> should match 
// service_traits::DataType< ::aquacore::SetNamedFloat > 
template<>
struct DataType< ::aquacore::SetNamedFloatResponse>
{
  static const char* value()
  {
    return DataType< ::aquacore::SetNamedFloat >::value();
  }
  static const char* value(const ::aquacore::SetNamedFloatResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AQUACORE_MESSAGE_SETNAMEDFLOAT_H
