// Generated by gencpp from file aquacore/SetPeriodicLegCommand.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_SETPERIODICLEGCOMMAND_H
#define AQUACORE_MESSAGE_SETPERIODICLEGCOMMAND_H

#include <ros/service_traits.h>


#include <aquacore/SetPeriodicLegCommandRequest.h>
#include <aquacore/SetPeriodicLegCommandResponse.h>


namespace aquacore
{

struct SetPeriodicLegCommand
{

typedef SetPeriodicLegCommandRequest Request;
typedef SetPeriodicLegCommandResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPeriodicLegCommand
} // namespace aquacore


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aquacore::SetPeriodicLegCommand > {
  static const char* value()
  {
    return "e706408018621c179fa26af34ef37d03";
  }

  static const char* value(const ::aquacore::SetPeriodicLegCommand&) { return value(); }
};

template<>
struct DataType< ::aquacore::SetPeriodicLegCommand > {
  static const char* value()
  {
    return "aquacore/SetPeriodicLegCommand";
  }

  static const char* value(const ::aquacore::SetPeriodicLegCommand&) { return value(); }
};


// service_traits::MD5Sum< ::aquacore::SetPeriodicLegCommandRequest> should match 
// service_traits::MD5Sum< ::aquacore::SetPeriodicLegCommand > 
template<>
struct MD5Sum< ::aquacore::SetPeriodicLegCommandRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::SetPeriodicLegCommand >::value();
  }
  static const char* value(const ::aquacore::SetPeriodicLegCommandRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::SetPeriodicLegCommandRequest> should match 
// service_traits::DataType< ::aquacore::SetPeriodicLegCommand > 
template<>
struct DataType< ::aquacore::SetPeriodicLegCommandRequest>
{
  static const char* value()
  {
    return DataType< ::aquacore::SetPeriodicLegCommand >::value();
  }
  static const char* value(const ::aquacore::SetPeriodicLegCommandRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aquacore::SetPeriodicLegCommandResponse> should match 
// service_traits::MD5Sum< ::aquacore::SetPeriodicLegCommand > 
template<>
struct MD5Sum< ::aquacore::SetPeriodicLegCommandResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::SetPeriodicLegCommand >::value();
  }
  static const char* value(const ::aquacore::SetPeriodicLegCommandResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::SetPeriodicLegCommandResponse> should match 
// service_traits::DataType< ::aquacore::SetPeriodicLegCommand > 
template<>
struct DataType< ::aquacore::SetPeriodicLegCommandResponse>
{
  static const char* value()
  {
    return DataType< ::aquacore::SetPeriodicLegCommand >::value();
  }
  static const char* value(const ::aquacore::SetPeriodicLegCommandResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AQUACORE_MESSAGE_SETPERIODICLEGCOMMAND_H
