// Generated by gencpp from file aquacore/SetPauseMode.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_SETPAUSEMODE_H
#define AQUACORE_MESSAGE_SETPAUSEMODE_H

#include <ros/service_traits.h>


#include <aquacore/SetPauseModeRequest.h>
#include <aquacore/SetPauseModeResponse.h>


namespace aquacore
{

struct SetPauseMode
{

typedef SetPauseModeRequest Request;
typedef SetPauseModeResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetPauseMode
} // namespace aquacore


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aquacore::SetPauseMode > {
  static const char* value()
  {
    return "313b4007c7badea2cfc258f5f204bf3a";
  }

  static const char* value(const ::aquacore::SetPauseMode&) { return value(); }
};

template<>
struct DataType< ::aquacore::SetPauseMode > {
  static const char* value()
  {
    return "aquacore/SetPauseMode";
  }

  static const char* value(const ::aquacore::SetPauseMode&) { return value(); }
};


// service_traits::MD5Sum< ::aquacore::SetPauseModeRequest> should match 
// service_traits::MD5Sum< ::aquacore::SetPauseMode > 
template<>
struct MD5Sum< ::aquacore::SetPauseModeRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::SetPauseMode >::value();
  }
  static const char* value(const ::aquacore::SetPauseModeRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::SetPauseModeRequest> should match 
// service_traits::DataType< ::aquacore::SetPauseMode > 
template<>
struct DataType< ::aquacore::SetPauseModeRequest>
{
  static const char* value()
  {
    return DataType< ::aquacore::SetPauseMode >::value();
  }
  static const char* value(const ::aquacore::SetPauseModeRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aquacore::SetPauseModeResponse> should match 
// service_traits::MD5Sum< ::aquacore::SetPauseMode > 
template<>
struct MD5Sum< ::aquacore::SetPauseModeResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::SetPauseMode >::value();
  }
  static const char* value(const ::aquacore::SetPauseModeResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::SetPauseModeResponse> should match 
// service_traits::DataType< ::aquacore::SetPauseMode > 
template<>
struct DataType< ::aquacore::SetPauseModeResponse>
{
  static const char* value()
  {
    return DataType< ::aquacore::SetPauseMode >::value();
  }
  static const char* value(const ::aquacore::SetPauseModeResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AQUACORE_MESSAGE_SETPAUSEMODE_H
