// Generated by gencpp from file aquacore/SetTargetLegAngles.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_SETTARGETLEGANGLES_H
#define AQUACORE_MESSAGE_SETTARGETLEGANGLES_H

#include <ros/service_traits.h>


#include <aquacore/SetTargetLegAnglesRequest.h>
#include <aquacore/SetTargetLegAnglesResponse.h>


namespace aquacore
{

struct SetTargetLegAngles
{

typedef SetTargetLegAnglesRequest Request;
typedef SetTargetLegAnglesResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTargetLegAngles
} // namespace aquacore


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aquacore::SetTargetLegAngles > {
  static const char* value()
  {
    return "713c56434b15577b0cfe5670a7e5dd0a";
  }

  static const char* value(const ::aquacore::SetTargetLegAngles&) { return value(); }
};

template<>
struct DataType< ::aquacore::SetTargetLegAngles > {
  static const char* value()
  {
    return "aquacore/SetTargetLegAngles";
  }

  static const char* value(const ::aquacore::SetTargetLegAngles&) { return value(); }
};


// service_traits::MD5Sum< ::aquacore::SetTargetLegAnglesRequest> should match 
// service_traits::MD5Sum< ::aquacore::SetTargetLegAngles > 
template<>
struct MD5Sum< ::aquacore::SetTargetLegAnglesRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::SetTargetLegAngles >::value();
  }
  static const char* value(const ::aquacore::SetTargetLegAnglesRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::SetTargetLegAnglesRequest> should match 
// service_traits::DataType< ::aquacore::SetTargetLegAngles > 
template<>
struct DataType< ::aquacore::SetTargetLegAnglesRequest>
{
  static const char* value()
  {
    return DataType< ::aquacore::SetTargetLegAngles >::value();
  }
  static const char* value(const ::aquacore::SetTargetLegAnglesRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aquacore::SetTargetLegAnglesResponse> should match 
// service_traits::MD5Sum< ::aquacore::SetTargetLegAngles > 
template<>
struct MD5Sum< ::aquacore::SetTargetLegAnglesResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::SetTargetLegAngles >::value();
  }
  static const char* value(const ::aquacore::SetTargetLegAnglesResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::SetTargetLegAnglesResponse> should match 
// service_traits::DataType< ::aquacore::SetTargetLegAngles > 
template<>
struct DataType< ::aquacore::SetTargetLegAnglesResponse>
{
  static const char* value()
  {
    return DataType< ::aquacore::SetTargetLegAngles >::value();
  }
  static const char* value(const ::aquacore::SetTargetLegAnglesResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AQUACORE_MESSAGE_SETTARGETLEGANGLES_H
