// Generated by gencpp from file aquacore/SetTargetDepth.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_SETTARGETDEPTH_H
#define AQUACORE_MESSAGE_SETTARGETDEPTH_H

#include <ros/service_traits.h>


#include <aquacore/SetTargetDepthRequest.h>
#include <aquacore/SetTargetDepthResponse.h>


namespace aquacore
{

struct SetTargetDepth
{

typedef SetTargetDepthRequest Request;
typedef SetTargetDepthResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct SetTargetDepth
} // namespace aquacore


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aquacore::SetTargetDepth > {
  static const char* value()
  {
    return "0c5e51c957e48bd29e418e983a93b9a7";
  }

  static const char* value(const ::aquacore::SetTargetDepth&) { return value(); }
};

template<>
struct DataType< ::aquacore::SetTargetDepth > {
  static const char* value()
  {
    return "aquacore/SetTargetDepth";
  }

  static const char* value(const ::aquacore::SetTargetDepth&) { return value(); }
};


// service_traits::MD5Sum< ::aquacore::SetTargetDepthRequest> should match 
// service_traits::MD5Sum< ::aquacore::SetTargetDepth > 
template<>
struct MD5Sum< ::aquacore::SetTargetDepthRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::SetTargetDepth >::value();
  }
  static const char* value(const ::aquacore::SetTargetDepthRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::SetTargetDepthRequest> should match 
// service_traits::DataType< ::aquacore::SetTargetDepth > 
template<>
struct DataType< ::aquacore::SetTargetDepthRequest>
{
  static const char* value()
  {
    return DataType< ::aquacore::SetTargetDepth >::value();
  }
  static const char* value(const ::aquacore::SetTargetDepthRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aquacore::SetTargetDepthResponse> should match 
// service_traits::MD5Sum< ::aquacore::SetTargetDepth > 
template<>
struct MD5Sum< ::aquacore::SetTargetDepthResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::SetTargetDepth >::value();
  }
  static const char* value(const ::aquacore::SetTargetDepthResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::SetTargetDepthResponse> should match 
// service_traits::DataType< ::aquacore::SetTargetDepth > 
template<>
struct DataType< ::aquacore::SetTargetDepthResponse>
{
  static const char* value()
  {
    return DataType< ::aquacore::SetTargetDepth >::value();
  }
  static const char* value(const ::aquacore::SetTargetDepthResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AQUACORE_MESSAGE_SETTARGETDEPTH_H
