// Generated by gencpp from file aquacore/StepSimulation.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_STEPSIMULATION_H
#define AQUACORE_MESSAGE_STEPSIMULATION_H

#include <ros/service_traits.h>


#include <aquacore/StepSimulationRequest.h>
#include <aquacore/StepSimulationResponse.h>


namespace aquacore
{

struct StepSimulation
{

typedef StepSimulationRequest Request;
typedef StepSimulationResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StepSimulation
} // namespace aquacore


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::aquacore::StepSimulation > {
  static const char* value()
  {
    return "b3f60a70b50fa6577110da716cb22455";
  }

  static const char* value(const ::aquacore::StepSimulation&) { return value(); }
};

template<>
struct DataType< ::aquacore::StepSimulation > {
  static const char* value()
  {
    return "aquacore/StepSimulation";
  }

  static const char* value(const ::aquacore::StepSimulation&) { return value(); }
};


// service_traits::MD5Sum< ::aquacore::StepSimulationRequest> should match 
// service_traits::MD5Sum< ::aquacore::StepSimulation > 
template<>
struct MD5Sum< ::aquacore::StepSimulationRequest>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::StepSimulation >::value();
  }
  static const char* value(const ::aquacore::StepSimulationRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::StepSimulationRequest> should match 
// service_traits::DataType< ::aquacore::StepSimulation > 
template<>
struct DataType< ::aquacore::StepSimulationRequest>
{
  static const char* value()
  {
    return DataType< ::aquacore::StepSimulation >::value();
  }
  static const char* value(const ::aquacore::StepSimulationRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::aquacore::StepSimulationResponse> should match 
// service_traits::MD5Sum< ::aquacore::StepSimulation > 
template<>
struct MD5Sum< ::aquacore::StepSimulationResponse>
{
  static const char* value()
  {
    return MD5Sum< ::aquacore::StepSimulation >::value();
  }
  static const char* value(const ::aquacore::StepSimulationResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::aquacore::StepSimulationResponse> should match 
// service_traits::DataType< ::aquacore::StepSimulation > 
template<>
struct DataType< ::aquacore::StepSimulationResponse>
{
  static const char* value()
  {
    return DataType< ::aquacore::StepSimulation >::value();
  }
  static const char* value(const ::aquacore::StepSimulationResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // AQUACORE_MESSAGE_STEPSIMULATION_H
