// Generated by gencpp from file aquacore/SurfaceTaskTypes.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_SURFACETASKTYPES_H
#define AQUACORE_MESSAGE_SURFACETASKTYPES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aquacore
{
template <class ContainerAllocator>
struct SurfaceTaskTypes_
{
  typedef SurfaceTaskTypes_<ContainerAllocator> Type;

  SurfaceTaskTypes_()
    {
    }
  SurfaceTaskTypes_(const ContainerAllocator& _alloc)
    {
    }




    enum { SURFACE = 0 };
     enum { WAIT_FOR_GPS_FIX = 1 };
     enum { STAY_ON_SURFACE = 2 };
 

  typedef boost::shared_ptr< ::aquacore::SurfaceTaskTypes_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aquacore::SurfaceTaskTypes_<ContainerAllocator> const> ConstPtr;

}; // struct SurfaceTaskTypes_

typedef ::aquacore::SurfaceTaskTypes_<std::allocator<void> > SurfaceTaskTypes;

typedef boost::shared_ptr< ::aquacore::SurfaceTaskTypes > SurfaceTaskTypesPtr;
typedef boost::shared_ptr< ::aquacore::SurfaceTaskTypes const> SurfaceTaskTypesConstPtr;

// constants requiring out of line definition

   

   

   



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aquacore::SurfaceTaskTypes_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aquacore::SurfaceTaskTypes_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aquacore

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'aquacore': ['/home/2014/tko4/robotAss1/src/aquacore/msg', '/home/2014/tko4/robotAss1/devel/share/aquacore/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aquacore::SurfaceTaskTypes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aquacore::SurfaceTaskTypes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aquacore::SurfaceTaskTypes_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aquacore::SurfaceTaskTypes_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aquacore::SurfaceTaskTypes_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aquacore::SurfaceTaskTypes_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aquacore::SurfaceTaskTypes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d902353c3ce8457f71121f1a0c1f3a87";
  }

  static const char* value(const ::aquacore::SurfaceTaskTypes_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd902353c3ce8457fULL;
  static const uint64_t static_value2 = 0x71121f1a0c1f3a87ULL;
};

template<class ContainerAllocator>
struct DataType< ::aquacore::SurfaceTaskTypes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aquacore/SurfaceTaskTypes";
  }

  static const char* value(const ::aquacore::SurfaceTaskTypes_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aquacore::SurfaceTaskTypes_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# See DoSurfaceTask.action/Goal/task\n\
byte SURFACE = 0\n\
byte WAIT_FOR_GPS_FIX = 1\n\
byte STAY_ON_SURFACE = 2\n\
";
  }

  static const char* value(const ::aquacore::SurfaceTaskTypes_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aquacore::SurfaceTaskTypes_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SurfaceTaskTypes_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aquacore::SurfaceTaskTypes_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::aquacore::SurfaceTaskTypes_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // AQUACORE_MESSAGE_SURFACETASKTYPES_H
