// Generated by gencpp from file aquacore/SwimForwardActionGoal.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_SWIMFORWARDACTIONGOAL_H
#define AQUACORE_MESSAGE_SWIMFORWARDACTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>
#include <actionlib_msgs/GoalID.h>
#include <aquacore/SwimForwardGoal.h>

namespace aquacore
{
template <class ContainerAllocator>
struct SwimForwardActionGoal_
{
  typedef SwimForwardActionGoal_<ContainerAllocator> Type;

  SwimForwardActionGoal_()
    : header()
    , goal_id()
    , goal()  {
    }
  SwimForwardActionGoal_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , goal_id(_alloc)
    , goal(_alloc)  {
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef  ::actionlib_msgs::GoalID_<ContainerAllocator>  _goal_id_type;
  _goal_id_type goal_id;

   typedef  ::aquacore::SwimForwardGoal_<ContainerAllocator>  _goal_type;
  _goal_type goal;




  typedef boost::shared_ptr< ::aquacore::SwimForwardActionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aquacore::SwimForwardActionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct SwimForwardActionGoal_

typedef ::aquacore::SwimForwardActionGoal_<std::allocator<void> > SwimForwardActionGoal;

typedef boost::shared_ptr< ::aquacore::SwimForwardActionGoal > SwimForwardActionGoalPtr;
typedef boost::shared_ptr< ::aquacore::SwimForwardActionGoal const> SwimForwardActionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aquacore::SwimForwardActionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aquacore::SwimForwardActionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aquacore

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': True}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'aquacore': ['/home/2014/tko4/robotAss1/src/aquacore/msg', '/home/2014/tko4/robotAss1/devel/share/aquacore/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aquacore::SwimForwardActionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aquacore::SwimForwardActionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aquacore::SwimForwardActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aquacore::SwimForwardActionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aquacore::SwimForwardActionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aquacore::SwimForwardActionGoal_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aquacore::SwimForwardActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "b588c6db3de822380c09ea3326ae8bbd";
  }

  static const char* value(const ::aquacore::SwimForwardActionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xb588c6db3de82238ULL;
  static const uint64_t static_value2 = 0x0c09ea3326ae8bbdULL;
};

template<class ContainerAllocator>
struct DataType< ::aquacore::SwimForwardActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aquacore/SwimForwardActionGoal";
  }

  static const char* value(const ::aquacore::SwimForwardActionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aquacore::SwimForwardActionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
\n\
Header header\n\
actionlib_msgs/GoalID goal_id\n\
SwimForwardGoal goal\n\
\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
\n\
================================================================================\n\
MSG: actionlib_msgs/GoalID\n\
# The stamp should store the time at which this goal was requested.\n\
# It is used by an action server when it tries to preempt all\n\
# goals that were requested before a certain time\n\
time stamp\n\
\n\
# The id provides a way to associate feedback and\n\
# result message with specific goal requests. The id\n\
# specified must be unique.\n\
string id\n\
\n\
\n\
================================================================================\n\
MSG: aquacore/SwimForwardGoal\n\
# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# BIG WARNING!!! It is potentially misleading that at the beginning the robot will turn\n\
#                to the target yaw, and then swim straight from that point onwards.  \n\
\n\
# Desired Goal\n\
float64 duration     # in s\n\
float64 speed        # in pseudo-unit-rate\n\
float32 target_depth # in m; set to -1 to use robot's current depth\n\
float32 target_yaw   # in deg; set to 361 to use robot's current yaw\n\
\n\
";
  }

  static const char* value(const ::aquacore::SwimForwardActionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aquacore::SwimForwardActionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.goal_id);
      stream.next(m.goal);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SwimForwardActionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aquacore::SwimForwardActionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aquacore::SwimForwardActionGoal_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "goal_id: ";
    s << std::endl;
    Printer< ::actionlib_msgs::GoalID_<ContainerAllocator> >::stream(s, indent + "  ", v.goal_id);
    s << indent << "goal: ";
    s << std::endl;
    Printer< ::aquacore::SwimForwardGoal_<ContainerAllocator> >::stream(s, indent + "  ", v.goal);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AQUACORE_MESSAGE_SWIMFORWARDACTIONGOAL_H
