// Generated by gencpp from file aquacore/SwimForwardGoal.msg
// DO NOT EDIT!


#ifndef AQUACORE_MESSAGE_SWIMFORWARDGOAL_H
#define AQUACORE_MESSAGE_SWIMFORWARDGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace aquacore
{
template <class ContainerAllocator>
struct SwimForwardGoal_
{
  typedef SwimForwardGoal_<ContainerAllocator> Type;

  SwimForwardGoal_()
    : duration(0.0)
    , speed(0.0)
    , target_depth(0.0)
    , target_yaw(0.0)  {
    }
  SwimForwardGoal_(const ContainerAllocator& _alloc)
    : duration(0.0)
    , speed(0.0)
    , target_depth(0.0)
    , target_yaw(0.0)  {
    }



   typedef double _duration_type;
  _duration_type duration;

   typedef double _speed_type;
  _speed_type speed;

   typedef float _target_depth_type;
  _target_depth_type target_depth;

   typedef float _target_yaw_type;
  _target_yaw_type target_yaw;




  typedef boost::shared_ptr< ::aquacore::SwimForwardGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aquacore::SwimForwardGoal_<ContainerAllocator> const> ConstPtr;

}; // struct SwimForwardGoal_

typedef ::aquacore::SwimForwardGoal_<std::allocator<void> > SwimForwardGoal;

typedef boost::shared_ptr< ::aquacore::SwimForwardGoal > SwimForwardGoalPtr;
typedef boost::shared_ptr< ::aquacore::SwimForwardGoal const> SwimForwardGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aquacore::SwimForwardGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aquacore::SwimForwardGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace aquacore

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/indigo/share/sensor_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/indigo/share/geometry_msgs/cmake/../msg'], 'actionlib_msgs': ['/opt/ros/indigo/share/actionlib_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/indigo/share/std_msgs/cmake/../msg'], 'aquacore': ['/home/2014/tko4/robotAss1/src/aquacore/msg', '/home/2014/tko4/robotAss1/devel/share/aquacore/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::aquacore::SwimForwardGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aquacore::SwimForwardGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aquacore::SwimForwardGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aquacore::SwimForwardGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aquacore::SwimForwardGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aquacore::SwimForwardGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aquacore::SwimForwardGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "8ab2a87faf8d41b41f51cfda0b7d6d34";
  }

  static const char* value(const ::aquacore::SwimForwardGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x8ab2a87faf8d41b4ULL;
  static const uint64_t static_value2 = 0x1f51cfda0b7d6d34ULL;
};

template<class ContainerAllocator>
struct DataType< ::aquacore::SwimForwardGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aquacore/SwimForwardGoal";
  }

  static const char* value(const ::aquacore::SwimForwardGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aquacore::SwimForwardGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
# BIG WARNING!!! It is potentially misleading that at the beginning the robot will turn\n\
#                to the target yaw, and then swim straight from that point onwards.  \n\
\n\
# Desired Goal\n\
float64 duration     # in s\n\
float64 speed        # in pseudo-unit-rate\n\
float32 target_depth # in m; set to -1 to use robot's current depth\n\
float32 target_yaw   # in deg; set to 361 to use robot's current yaw\n\
\n\
";
  }

  static const char* value(const ::aquacore::SwimForwardGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aquacore::SwimForwardGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.duration);
      stream.next(m.speed);
      stream.next(m.target_depth);
      stream.next(m.target_yaw);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER;
  }; // struct SwimForwardGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aquacore::SwimForwardGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aquacore::SwimForwardGoal_<ContainerAllocator>& v)
  {
    s << indent << "duration: ";
    Printer<double>::stream(s, indent + "  ", v.duration);
    s << indent << "speed: ";
    Printer<double>::stream(s, indent + "  ", v.speed);
    s << indent << "target_depth: ";
    Printer<float>::stream(s, indent + "  ", v.target_depth);
    s << indent << "target_yaw: ";
    Printer<float>::stream(s, indent + "  ", v.target_yaw);
  }
};

} // namespace message_operations
} // namespace ros

#endif // AQUACORE_MESSAGE_SWIMFORWARDGOAL_H
