//#line 2 "/opt/ros/indigo/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"
// *********************************************************
// 
// File autogenerated for the aquaautopilot package 
// by the dynamic_reconfigure package.
// Please do not edit.
// 
// ********************************************************/

#ifndef __aquaautopilot__AUTOPILOTCONFIG_H__
#define __aquaautopilot__AUTOPILOTCONFIG_H__

#include <dynamic_reconfigure/config_tools.h>
#include <limits>
#include <ros/node_handle.h>
#include <dynamic_reconfigure/ConfigDescription.h>
#include <dynamic_reconfigure/ParamDescription.h>
#include <dynamic_reconfigure/Group.h>
#include <dynamic_reconfigure/config_init_mutex.h>
#include <boost/any.hpp>

namespace aquaautopilot
{
  class AutopilotConfigStatics;
  
  class AutopilotConfig
  {
  public:
    class AbstractParamDescription : public dynamic_reconfigure::ParamDescription
    {
    public:
      AbstractParamDescription(std::string n, std::string t, uint32_t l, 
          std::string d, std::string e)
      {
        name = n;
        type = t;
        level = l;
        description = d;
        edit_method = e;
      }
      
      virtual void clamp(AutopilotConfig &config, const AutopilotConfig &max, const AutopilotConfig &min) const = 0;
      virtual void calcLevel(uint32_t &level, const AutopilotConfig &config1, const AutopilotConfig &config2) const = 0;
      virtual void fromServer(const ros::NodeHandle &nh, AutopilotConfig &config) const = 0;
      virtual void toServer(const ros::NodeHandle &nh, const AutopilotConfig &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, AutopilotConfig &config) const = 0;
      virtual void toMessage(dynamic_reconfigure::Config &msg, const AutopilotConfig &config) const = 0;
      virtual void getValue(const AutopilotConfig &config, boost::any &val) const = 0;
    };

    typedef boost::shared_ptr<AbstractParamDescription> AbstractParamDescriptionPtr;
    typedef boost::shared_ptr<const AbstractParamDescription> AbstractParamDescriptionConstPtr;
    
    template <class T>
    class ParamDescription : public AbstractParamDescription
    {
    public:
      ParamDescription(std::string name, std::string type, uint32_t level, 
          std::string description, std::string edit_method, T AutopilotConfig::* f) :
        AbstractParamDescription(name, type, level, description, edit_method),
        field(f)
      {}

      T (AutopilotConfig::* field);

      virtual void clamp(AutopilotConfig &config, const AutopilotConfig &max, const AutopilotConfig &min) const
      {
        if (config.*field > max.*field)
          config.*field = max.*field;
        
        if (config.*field < min.*field)
          config.*field = min.*field;
      }

      virtual void calcLevel(uint32_t &comb_level, const AutopilotConfig &config1, const AutopilotConfig &config2) const
      {
        if (config1.*field != config2.*field)
          comb_level |= level;
      }

      virtual void fromServer(const ros::NodeHandle &nh, AutopilotConfig &config) const
      {
        nh.getParam(name, config.*field);
      }

      virtual void toServer(const ros::NodeHandle &nh, const AutopilotConfig &config) const
      {
        nh.setParam(name, config.*field);
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, AutopilotConfig &config) const
      {
        return dynamic_reconfigure::ConfigTools::getParameter(msg, name, config.*field);
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const AutopilotConfig &config) const
      {
        dynamic_reconfigure::ConfigTools::appendParameter(msg, name, config.*field);
      }

      virtual void getValue(const AutopilotConfig &config, boost::any &val) const
      {
        val = config.*field;
      }
    };

    class AbstractGroupDescription : public dynamic_reconfigure::Group
    {
      public:
      AbstractGroupDescription(std::string n, std::string t, int p, int i, bool s)
      {
        name = n;
        type = t;
        parent = p;
        state = s;
        id = i;
      }

      std::vector<AbstractParamDescriptionConstPtr> abstract_parameters;
      bool state;

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &config) const = 0;
      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &config) const =0;
      virtual void updateParams(boost::any &cfg, AutopilotConfig &top) const= 0;
      virtual void setInitialState(boost::any &cfg) const = 0;


      void convertParams()
      {
        for(std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = abstract_parameters.begin(); i != abstract_parameters.end(); ++i)
        {
          parameters.push_back(dynamic_reconfigure::ParamDescription(**i));
        }
      }
    };

    typedef boost::shared_ptr<AbstractGroupDescription> AbstractGroupDescriptionPtr;
    typedef boost::shared_ptr<const AbstractGroupDescription> AbstractGroupDescriptionConstPtr;

    template<class T, class PT>
    class GroupDescription : public AbstractGroupDescription
    {
    public:
      GroupDescription(std::string name, std::string type, int parent, int id, bool s, T PT::* f) : AbstractGroupDescription(name, type, parent, id, s), field(f)
      {
      }

      GroupDescription(const GroupDescription<T, PT>& g): AbstractGroupDescription(g.name, g.type, g.parent, g.id, g.state), field(g.field), groups(g.groups)
      {
        parameters = g.parameters;
        abstract_parameters = g.abstract_parameters;
      }

      virtual bool fromMessage(const dynamic_reconfigure::Config &msg, boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        if(!dynamic_reconfigure::ConfigTools::getGroupState(msg, name, (*config).*field))
          return false;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          if(!(*i)->fromMessage(msg, n))
            return false;
        }

        return true;
      }

      virtual void setInitialState(boost::any &cfg) const
      {
        PT* config = boost::any_cast<PT*>(cfg);
        T* group = &((*config).*field);
        group->state = state;

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = boost::any(&((*config).*field));
          (*i)->setInitialState(n);
        }

      }

      virtual void updateParams(boost::any &cfg, AutopilotConfig &top) const
      {
        PT* config = boost::any_cast<PT*>(cfg);

        T* f = &((*config).*field);
        f->setParams(top, abstract_parameters);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          boost::any n = &((*config).*field);
          (*i)->updateParams(n, top);
        }
      }

      virtual void toMessage(dynamic_reconfigure::Config &msg, const boost::any &cfg) const
      {
        const PT config = boost::any_cast<PT>(cfg);
        dynamic_reconfigure::ConfigTools::appendGroup<T>(msg, name, id, parent, config.*field);

        for(std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = groups.begin(); i != groups.end(); ++i)
        {
          (*i)->toMessage(msg, config.*field);
        }
      }

      T (PT::* field);
      std::vector<AutopilotConfig::AbstractGroupDescriptionConstPtr> groups;
    };
    
class DEFAULT
{
  public:
    DEFAULT()
    {
      state = true;
      name = "Default";
    }

    void setParams(AutopilotConfig &config, const std::vector<AbstractParamDescriptionConstPtr> params)
    {
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator _i = params.begin(); _i != params.end(); ++_i)
      {
        boost::any val;
        (*_i)->getValue(config, val);

        if("ROLL_P_GAIN"==(*_i)->name){ROLL_P_GAIN = boost::any_cast<double>(val);}
        if("PITCH_P_GAIN"==(*_i)->name){PITCH_P_GAIN = boost::any_cast<double>(val);}
        if("YAW_P_GAIN"==(*_i)->name){YAW_P_GAIN = boost::any_cast<double>(val);}
        if("ROLL_I_GAIN"==(*_i)->name){ROLL_I_GAIN = boost::any_cast<double>(val);}
        if("PITCH_I_GAIN"==(*_i)->name){PITCH_I_GAIN = boost::any_cast<double>(val);}
        if("YAW_I_GAIN"==(*_i)->name){YAW_I_GAIN = boost::any_cast<double>(val);}
        if("ROLL_D_GAIN"==(*_i)->name){ROLL_D_GAIN = boost::any_cast<double>(val);}
        if("PITCH_D_GAIN"==(*_i)->name){PITCH_D_GAIN = boost::any_cast<double>(val);}
        if("YAW_D_GAIN"==(*_i)->name){YAW_D_GAIN = boost::any_cast<double>(val);}
        if("ROLL_CONST_GAIN"==(*_i)->name){ROLL_CONST_GAIN = boost::any_cast<double>(val);}
        if("ROLL_D_FILTER_PERIOD"==(*_i)->name){ROLL_D_FILTER_PERIOD = boost::any_cast<double>(val);}
        if("PITCH_D_FILTER_PERIOD"==(*_i)->name){PITCH_D_FILTER_PERIOD = boost::any_cast<double>(val);}
        if("YAW_D_FILTER_PERIOD"==(*_i)->name){YAW_D_FILTER_PERIOD = boost::any_cast<double>(val);}
        if("MAX_INTEGRAL_ANGLE_ERROR"==(*_i)->name){MAX_INTEGRAL_ANGLE_ERROR = boost::any_cast<double>(val);}
        if("KSPEED"==(*_i)->name){KSPEED = boost::any_cast<double>(val);}
        if("KHEAVE"==(*_i)->name){KHEAVE = boost::any_cast<double>(val);}
        if("KDEPTH"==(*_i)->name){KDEPTH = boost::any_cast<double>(val);}
        if("DEPTH_D_GAIN"==(*_i)->name){DEPTH_D_GAIN = boost::any_cast<double>(val);}
        if("DEPTH_D_FILTER_PERIOD"==(*_i)->name){DEPTH_D_FILTER_PERIOD = boost::any_cast<double>(val);}
        if("MAX_ROLL"==(*_i)->name){MAX_ROLL = boost::any_cast<double>(val);}
        if("MAX_PITCH"==(*_i)->name){MAX_PITCH = boost::any_cast<double>(val);}
        if("MAX_YAW"==(*_i)->name){MAX_YAW = boost::any_cast<double>(val);}
        if("MAX_SPEED"==(*_i)->name){MAX_SPEED = boost::any_cast<double>(val);}
        if("MAX_HEAVE"==(*_i)->name){MAX_HEAVE = boost::any_cast<double>(val);}
      }
    }

    double ROLL_P_GAIN;
double PITCH_P_GAIN;
double YAW_P_GAIN;
double ROLL_I_GAIN;
double PITCH_I_GAIN;
double YAW_I_GAIN;
double ROLL_D_GAIN;
double PITCH_D_GAIN;
double YAW_D_GAIN;
double ROLL_CONST_GAIN;
double ROLL_D_FILTER_PERIOD;
double PITCH_D_FILTER_PERIOD;
double YAW_D_FILTER_PERIOD;
double MAX_INTEGRAL_ANGLE_ERROR;
double KSPEED;
double KHEAVE;
double KDEPTH;
double DEPTH_D_GAIN;
double DEPTH_D_FILTER_PERIOD;
double MAX_ROLL;
double MAX_PITCH;
double MAX_YAW;
double MAX_SPEED;
double MAX_HEAVE;

    bool state;
    std::string name;

    
}groups;



//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double ROLL_P_GAIN;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double PITCH_P_GAIN;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double YAW_P_GAIN;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double ROLL_I_GAIN;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double PITCH_I_GAIN;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double YAW_I_GAIN;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double ROLL_D_GAIN;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double PITCH_D_GAIN;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double YAW_D_GAIN;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double ROLL_CONST_GAIN;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double ROLL_D_FILTER_PERIOD;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double PITCH_D_FILTER_PERIOD;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double YAW_D_FILTER_PERIOD;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double MAX_INTEGRAL_ANGLE_ERROR;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double KSPEED;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double KHEAVE;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double KDEPTH;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double DEPTH_D_GAIN;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double DEPTH_D_FILTER_PERIOD;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double MAX_ROLL;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double MAX_PITCH;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double MAX_YAW;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double MAX_SPEED;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      double MAX_HEAVE;
//#line 218 "/opt/ros/indigo/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

    bool __fromMessage__(dynamic_reconfigure::Config &msg)
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();

      int count = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        if ((*i)->fromMessage(msg, *this))
          count++;

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i ++)
      {
        if ((*i)->id == 0)
        {
          boost::any n = boost::any(this);
          (*i)->updateParams(n, *this);
          (*i)->fromMessage(msg, n);
        }
      }

      if (count != dynamic_reconfigure::ConfigTools::size(msg))
      {
        ROS_ERROR("AutopilotConfig::__fromMessage__ called with an unexpected parameter.");
        ROS_ERROR("Booleans:");
        for (unsigned int i = 0; i < msg.bools.size(); i++)
          ROS_ERROR("  %s", msg.bools[i].name.c_str());
        ROS_ERROR("Integers:");
        for (unsigned int i = 0; i < msg.ints.size(); i++)
          ROS_ERROR("  %s", msg.ints[i].name.c_str());
        ROS_ERROR("Doubles:");
        for (unsigned int i = 0; i < msg.doubles.size(); i++)
          ROS_ERROR("  %s", msg.doubles[i].name.c_str());
        ROS_ERROR("Strings:");
        for (unsigned int i = 0; i < msg.strs.size(); i++)
          ROS_ERROR("  %s", msg.strs[i].name.c_str());
        // @todo Check that there are no duplicates. Make this error more
        // explicit.
        return false;
      }
      return true;
    }

    // This version of __toMessage__ is used during initialization of
    // statics when __getParamDescriptions__ can't be called yet.
    void __toMessage__(dynamic_reconfigure::Config &msg, const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__, const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__) const
    {
      dynamic_reconfigure::ConfigTools::clear(msg);
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toMessage(msg, *this);

      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        if((*i)->id == 0)
        {
          (*i)->toMessage(msg, *this);
        }
      }
    }
    
    void __toMessage__(dynamic_reconfigure::Config &msg) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      __toMessage__(msg, __param_descriptions__, __group_descriptions__);
    }
    
    void __toServer__(const ros::NodeHandle &nh) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->toServer(nh, *this);
    }

    void __fromServer__(const ros::NodeHandle &nh)
    {
      static bool setup=false;

      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->fromServer(nh, *this);

      const std::vector<AbstractGroupDescriptionConstPtr> &__group_descriptions__ = __getGroupDescriptions__();
      for (std::vector<AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); i++){
        if (!setup && (*i)->id == 0) {
          setup = true;
          boost::any n = boost::any(this);
          (*i)->setInitialState(n);
        }
      }
    }

    void __clamp__()
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      const AutopilotConfig &__max__ = __getMax__();
      const AutopilotConfig &__min__ = __getMin__();
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->clamp(*this, __max__, __min__);
    }

    uint32_t __level__(const AutopilotConfig &config) const
    {
      const std::vector<AbstractParamDescriptionConstPtr> &__param_descriptions__ = __getParamDescriptions__();
      uint32_t level = 0;
      for (std::vector<AbstractParamDescriptionConstPtr>::const_iterator i = __param_descriptions__.begin(); i != __param_descriptions__.end(); ++i)
        (*i)->calcLevel(level, config, *this);
      return level;
    }
    
    static const dynamic_reconfigure::ConfigDescription &__getDescriptionMessage__();
    static const AutopilotConfig &__getDefault__();
    static const AutopilotConfig &__getMax__();
    static const AutopilotConfig &__getMin__();
    static const std::vector<AbstractParamDescriptionConstPtr> &__getParamDescriptions__();
    static const std::vector<AbstractGroupDescriptionConstPtr> &__getGroupDescriptions__();
    
  private:
    static const AutopilotConfigStatics *__get_statics__();
  };
  
  template <> // Max and min are ignored for strings.
  inline void AutopilotConfig::ParamDescription<std::string>::clamp(AutopilotConfig &config, const AutopilotConfig &max, const AutopilotConfig &min) const
  {
    return;
  }

  class AutopilotConfigStatics
  {
    friend class AutopilotConfig;
    
    AutopilotConfigStatics()
    {
AutopilotConfig::GroupDescription<AutopilotConfig::DEFAULT, AutopilotConfig> Default("Default", "", 0, 0, true, &AutopilotConfig::groups);
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.ROLL_P_GAIN = -5.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.ROLL_P_GAIN = 5.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.ROLL_P_GAIN = 1.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("ROLL_P_GAIN", "double", 0, "Proportional gain for roll", "", &AutopilotConfig::ROLL_P_GAIN)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("ROLL_P_GAIN", "double", 0, "Proportional gain for roll", "", &AutopilotConfig::ROLL_P_GAIN)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.PITCH_P_GAIN = -5.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.PITCH_P_GAIN = 5.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.PITCH_P_GAIN = 1.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("PITCH_P_GAIN", "double", 0, "Proportional gain for pitch", "", &AutopilotConfig::PITCH_P_GAIN)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("PITCH_P_GAIN", "double", 0, "Proportional gain for pitch", "", &AutopilotConfig::PITCH_P_GAIN)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.YAW_P_GAIN = -5.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.YAW_P_GAIN = 5.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.YAW_P_GAIN = -1.5;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("YAW_P_GAIN", "double", 0, "Proportional gain for yaw", "", &AutopilotConfig::YAW_P_GAIN)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("YAW_P_GAIN", "double", 0, "Proportional gain for yaw", "", &AutopilotConfig::YAW_P_GAIN)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.ROLL_I_GAIN = -5.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.ROLL_I_GAIN = 5.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.ROLL_I_GAIN = 0.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("ROLL_I_GAIN", "double", 0, "Integral gain for roll", "", &AutopilotConfig::ROLL_I_GAIN)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("ROLL_I_GAIN", "double", 0, "Integral gain for roll", "", &AutopilotConfig::ROLL_I_GAIN)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.PITCH_I_GAIN = -5.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.PITCH_I_GAIN = 5.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.PITCH_I_GAIN = 0.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("PITCH_I_GAIN", "double", 0, "Integral gain for pitch", "", &AutopilotConfig::PITCH_I_GAIN)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("PITCH_I_GAIN", "double", 0, "Integral gain for pitch", "", &AutopilotConfig::PITCH_I_GAIN)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.YAW_I_GAIN = -5.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.YAW_I_GAIN = 5.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.YAW_I_GAIN = 0.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("YAW_I_GAIN", "double", 0, "Integral gain for yaw", "", &AutopilotConfig::YAW_I_GAIN)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("YAW_I_GAIN", "double", 0, "Integral gain for yaw", "", &AutopilotConfig::YAW_I_GAIN)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.ROLL_D_GAIN = -5.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.ROLL_D_GAIN = 5.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.ROLL_D_GAIN = 0.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("ROLL_D_GAIN", "double", 0, "Derivative gain for roll", "", &AutopilotConfig::ROLL_D_GAIN)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("ROLL_D_GAIN", "double", 0, "Derivative gain for roll", "", &AutopilotConfig::ROLL_D_GAIN)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.PITCH_D_GAIN = -5.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.PITCH_D_GAIN = 5.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.PITCH_D_GAIN = 0.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("PITCH_D_GAIN", "double", 0, "Derivative gain for pitch", "", &AutopilotConfig::PITCH_D_GAIN)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("PITCH_D_GAIN", "double", 0, "Derivative gain for pitch", "", &AutopilotConfig::PITCH_D_GAIN)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.YAW_D_GAIN = -5.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.YAW_D_GAIN = 5.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.YAW_D_GAIN = 0.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("YAW_D_GAIN", "double", 0, "Derivative gain for yaw", "", &AutopilotConfig::YAW_D_GAIN)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("YAW_D_GAIN", "double", 0, "Derivative gain for yaw", "", &AutopilotConfig::YAW_D_GAIN)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.ROLL_CONST_GAIN = -5.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.ROLL_CONST_GAIN = 5.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.ROLL_CONST_GAIN = 0.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("ROLL_CONST_GAIN", "double", 0, "Constant gain for roll, useful when heaving sideways", "", &AutopilotConfig::ROLL_CONST_GAIN)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("ROLL_CONST_GAIN", "double", 0, "Constant gain for roll, useful when heaving sideways", "", &AutopilotConfig::ROLL_CONST_GAIN)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.ROLL_D_FILTER_PERIOD = 0.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.ROLL_D_FILTER_PERIOD = 10.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.ROLL_D_FILTER_PERIOD = 0.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("ROLL_D_FILTER_PERIOD", "double", 0, "Time period for roll deriv exp filtering (s)", "", &AutopilotConfig::ROLL_D_FILTER_PERIOD)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("ROLL_D_FILTER_PERIOD", "double", 0, "Time period for roll deriv exp filtering (s)", "", &AutopilotConfig::ROLL_D_FILTER_PERIOD)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.PITCH_D_FILTER_PERIOD = 0.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.PITCH_D_FILTER_PERIOD = 10.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.PITCH_D_FILTER_PERIOD = 0.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("PITCH_D_FILTER_PERIOD", "double", 0, "Time period for pitch deriv exp filtering (s)", "", &AutopilotConfig::PITCH_D_FILTER_PERIOD)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("PITCH_D_FILTER_PERIOD", "double", 0, "Time period for pitch deriv exp filtering (s)", "", &AutopilotConfig::PITCH_D_FILTER_PERIOD)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.YAW_D_FILTER_PERIOD = 0.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.YAW_D_FILTER_PERIOD = 10.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.YAW_D_FILTER_PERIOD = 0.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("YAW_D_FILTER_PERIOD", "double", 0, "Time period for yaw deriv exp filtering (s)", "", &AutopilotConfig::YAW_D_FILTER_PERIOD)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("YAW_D_FILTER_PERIOD", "double", 0, "Time period for yaw deriv exp filtering (s)", "", &AutopilotConfig::YAW_D_FILTER_PERIOD)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.MAX_INTEGRAL_ANGLE_ERROR = -10.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.MAX_INTEGRAL_ANGLE_ERROR = 10.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.MAX_INTEGRAL_ANGLE_ERROR = 0.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("MAX_INTEGRAL_ANGLE_ERROR", "double", 0, "Maximum value for angle integration", "", &AutopilotConfig::MAX_INTEGRAL_ANGLE_ERROR)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("MAX_INTEGRAL_ANGLE_ERROR", "double", 0, "Maximum value for angle integration", "", &AutopilotConfig::MAX_INTEGRAL_ANGLE_ERROR)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.KSPEED = -3.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.KSPEED = 3.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.KSPEED = 1.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("KSPEED", "double", 0, "Proportional gain for forward velocity", "", &AutopilotConfig::KSPEED)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("KSPEED", "double", 0, "Proportional gain for forward velocity", "", &AutopilotConfig::KSPEED)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.KHEAVE = -3.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.KHEAVE = 3.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.KHEAVE = 1.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("KHEAVE", "double", 0, "Proportional gain for heave velocity", "", &AutopilotConfig::KHEAVE)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("KHEAVE", "double", 0, "Proportional gain for heave velocity", "", &AutopilotConfig::KHEAVE)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.KDEPTH = -10.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.KDEPTH = 10.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.KDEPTH = -1.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("KDEPTH", "double", 0, "Proportional gain for depth change", "", &AutopilotConfig::KDEPTH)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("KDEPTH", "double", 0, "Proportional gain for depth change", "", &AutopilotConfig::KDEPTH)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.DEPTH_D_GAIN = -10.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.DEPTH_D_GAIN = 10.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.DEPTH_D_GAIN = 0.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("DEPTH_D_GAIN", "double", 0, "Derivative gain for depth change", "", &AutopilotConfig::DEPTH_D_GAIN)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("DEPTH_D_GAIN", "double", 0, "Derivative gain for depth change", "", &AutopilotConfig::DEPTH_D_GAIN)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.DEPTH_D_FILTER_PERIOD = 0.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.DEPTH_D_FILTER_PERIOD = 10.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.DEPTH_D_FILTER_PERIOD = 0.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("DEPTH_D_FILTER_PERIOD", "double", 0, "Time period for depth deriv exp filtering (s)", "", &AutopilotConfig::DEPTH_D_FILTER_PERIOD)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("DEPTH_D_FILTER_PERIOD", "double", 0, "Time period for depth deriv exp filtering (s)", "", &AutopilotConfig::DEPTH_D_FILTER_PERIOD)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.MAX_ROLL = 0.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.MAX_ROLL = 1.6;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.MAX_ROLL = 1.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("MAX_ROLL", "double", 0, "Saturation threshold for roll, in radians", "", &AutopilotConfig::MAX_ROLL)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("MAX_ROLL", "double", 0, "Saturation threshold for roll, in radians", "", &AutopilotConfig::MAX_ROLL)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.MAX_PITCH = 0.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.MAX_PITCH = 1.6;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.MAX_PITCH = 1.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("MAX_PITCH", "double", 0, "Saturation threshold for pitch, in radians", "", &AutopilotConfig::MAX_PITCH)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("MAX_PITCH", "double", 0, "Saturation threshold for pitch, in radians", "", &AutopilotConfig::MAX_PITCH)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.MAX_YAW = 0.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.MAX_YAW = 1.6;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.MAX_YAW = 1.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("MAX_YAW", "double", 0, "Saturation threshold for yaw, in radians", "", &AutopilotConfig::MAX_YAW)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("MAX_YAW", "double", 0, "Saturation threshold for yaw, in radians", "", &AutopilotConfig::MAX_YAW)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.MAX_SPEED = 0.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.MAX_SPEED = 1.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.MAX_SPEED = 1.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("MAX_SPEED", "double", 0, "Saturation threshold for speed, in pseudo-velocity", "", &AutopilotConfig::MAX_SPEED)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("MAX_SPEED", "double", 0, "Saturation threshold for speed, in pseudo-velocity", "", &AutopilotConfig::MAX_SPEED)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __min__.MAX_HEAVE = 0.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __max__.MAX_HEAVE = 1.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __default__.MAX_HEAVE = 1.0;
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.abstract_parameters.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("MAX_HEAVE", "double", 0, "Saturation threshold for heave, in pseudo-velocity", "", &AutopilotConfig::MAX_HEAVE)));
//#line 262 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __param_descriptions__.push_back(AutopilotConfig::AbstractParamDescriptionConstPtr(new AutopilotConfig::ParamDescription<double>("MAX_HEAVE", "double", 0, "Saturation threshold for heave, in pseudo-velocity", "", &AutopilotConfig::MAX_HEAVE)));
//#line 233 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      Default.convertParams();
//#line 233 "/opt/ros/indigo/lib/python2.7/dist-packages/dynamic_reconfigure/parameter_generator_catkin.py"
      __group_descriptions__.push_back(AutopilotConfig::AbstractGroupDescriptionConstPtr(new AutopilotConfig::GroupDescription<AutopilotConfig::DEFAULT, AutopilotConfig>(Default)));
//#line 353 "/opt/ros/indigo/share/dynamic_reconfigure/cmake/../templates/ConfigType.h.template"

      for (std::vector<AutopilotConfig::AbstractGroupDescriptionConstPtr>::const_iterator i = __group_descriptions__.begin(); i != __group_descriptions__.end(); ++i)
      {
        __description_message__.groups.push_back(**i);
      }
      __max__.__toMessage__(__description_message__.max, __param_descriptions__, __group_descriptions__); 
      __min__.__toMessage__(__description_message__.min, __param_descriptions__, __group_descriptions__); 
      __default__.__toMessage__(__description_message__.dflt, __param_descriptions__, __group_descriptions__); 
    }
    std::vector<AutopilotConfig::AbstractParamDescriptionConstPtr> __param_descriptions__;
    std::vector<AutopilotConfig::AbstractGroupDescriptionConstPtr> __group_descriptions__;
    AutopilotConfig __max__;
    AutopilotConfig __min__;
    AutopilotConfig __default__;
    dynamic_reconfigure::ConfigDescription __description_message__;

    static const AutopilotConfigStatics *get_instance()
    {
      // Split this off in a separate function because I know that
      // instance will get initialized the first time get_instance is
      // called, and I am guaranteeing that get_instance gets called at
      // most once.
      static AutopilotConfigStatics instance;
      return &instance;
    }
  };

  inline const dynamic_reconfigure::ConfigDescription &AutopilotConfig::__getDescriptionMessage__() 
  {
    return __get_statics__()->__description_message__;
  }

  inline const AutopilotConfig &AutopilotConfig::__getDefault__()
  {
    return __get_statics__()->__default__;
  }
  
  inline const AutopilotConfig &AutopilotConfig::__getMax__()
  {
    return __get_statics__()->__max__;
  }
  
  inline const AutopilotConfig &AutopilotConfig::__getMin__()
  {
    return __get_statics__()->__min__;
  }
  
  inline const std::vector<AutopilotConfig::AbstractParamDescriptionConstPtr> &AutopilotConfig::__getParamDescriptions__()
  {
    return __get_statics__()->__param_descriptions__;
  }

  inline const std::vector<AutopilotConfig::AbstractGroupDescriptionConstPtr> &AutopilotConfig::__getGroupDescriptions__()
  {
    return __get_statics__()->__group_descriptions__;
  }

  inline const AutopilotConfigStatics *AutopilotConfig::__get_statics__()
  {
    const static AutopilotConfigStatics *statics;
  
    if (statics) // Common case
      return statics;

    boost::mutex::scoped_lock lock(dynamic_reconfigure::__init_mutex__);

    if (statics) // In case we lost a race.
      return statics;

    statics = AutopilotConfigStatics::get_instance();
    
    return statics;
  }


}

#endif // __AUTOPILOTRECONFIGURATOR_H__
